// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import { NativeModules, Platform } from "react-native";
import PushNotification from "react-native-push-notification";

/**
 * Cancels all pending scheduled notifications.
 * @returns {Promise.<void>}
 */
export async function CancelAllScheduledNotifications(): Promise<void> {
    // BEGIN USER CODE
    // Documentation https://github.com/zo0r/react-native-push-notification
    const isIOS = Platform.OS === "ios";
    if (
        NativeModules &&
        ((isIOS && !NativeModules.RNCPushNotificationIOS) || (!isIOS && !NativeModules.RNPushNotification))
    ) {
        return Promise.reject(new Error("Notifications module is not available in your app"));
    }

    PushNotification.cancelAllLocalNotifications();
    return Promise.resolve();

    // END USER CODE
}
