// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import Base64 from "js-base64";

/**
 * @param {string} inputString
 * @returns {Promise.<string>}
 */
export async function Base64Decode(inputString: string): Promise<string> {
    // BEGIN USER CODE
    return Base64.decode(inputString);
    // END USER CODE
}
