// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testsuite.proxies;

public class Campaign
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject campaignMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestSuite.Campaign";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Average("Average"),
		Name("Name"),
		AverageLong("AverageLong"),
		AverageInterger("AverageInterger");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Campaign(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestSuite.Campaign"));
	}

	protected Campaign(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject campaignMendixObject)
	{
		if (campaignMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TestSuite.Campaign", campaignMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestSuite.Campaign");

		this.campaignMendixObject = campaignMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Campaign.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static testsuite.proxies.Campaign initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testsuite.proxies.Campaign.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static testsuite.proxies.Campaign initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testsuite.proxies.Campaign(context, mendixObject);
	}

	public static testsuite.proxies.Campaign load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testsuite.proxies.Campaign.initialize(context, mendixObject);
	}

	public static java.util.List<testsuite.proxies.Campaign> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testsuite.proxies.Campaign> result = new java.util.ArrayList<testsuite.proxies.Campaign>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TestSuite.Campaign" + xpathConstraint))
			result.add(testsuite.proxies.Campaign.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Average
	 */
	public final java.math.BigDecimal getAverage()
	{
		return getAverage(getContext());
	}

	/**
	 * @param context
	 * @return value of Average
	 */
	public final java.math.BigDecimal getAverage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Average.toString());
	}

	/**
	 * Set value of Average
	 * @param average
	 */
	public final void setAverage(java.math.BigDecimal average)
	{
		setAverage(getContext(), average);
	}

	/**
	 * Set value of Average
	 * @param context
	 * @param average
	 */
	public final void setAverage(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal average)
	{
		getMendixObject().setValue(context, MemberNames.Average.toString(), average);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of AverageLong
	 */
	public final java.lang.Long getAverageLong()
	{
		return getAverageLong(getContext());
	}

	/**
	 * @param context
	 * @return value of AverageLong
	 */
	public final java.lang.Long getAverageLong(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.AverageLong.toString());
	}

	/**
	 * Set value of AverageLong
	 * @param averagelong
	 */
	public final void setAverageLong(java.lang.Long averagelong)
	{
		setAverageLong(getContext(), averagelong);
	}

	/**
	 * Set value of AverageLong
	 * @param context
	 * @param averagelong
	 */
	public final void setAverageLong(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long averagelong)
	{
		getMendixObject().setValue(context, MemberNames.AverageLong.toString(), averagelong);
	}

	/**
	 * @return value of AverageInterger
	 */
	public final java.lang.Integer getAverageInterger()
	{
		return getAverageInterger(getContext());
	}

	/**
	 * @param context
	 * @return value of AverageInterger
	 */
	public final java.lang.Integer getAverageInterger(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.AverageInterger.toString());
	}

	/**
	 * Set value of AverageInterger
	 * @param averageinterger
	 */
	public final void setAverageInterger(java.lang.Integer averageinterger)
	{
		setAverageInterger(getContext(), averageinterger);
	}

	/**
	 * Set value of AverageInterger
	 * @param context
	 * @param averageinterger
	 */
	public final void setAverageInterger(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer averageinterger)
	{
		getMendixObject().setValue(context, MemberNames.AverageInterger.toString(), averageinterger);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return campaignMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testsuite.proxies.Campaign that = (testsuite.proxies.Campaign) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestSuite.Campaign";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
