// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testsuite.proxies;

public class Rate
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject rateMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestSuite.Rate";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Rating("Rating"),
		RatingLong("RatingLong"),
		RatingInteger("RatingInteger"),
		Rate_Campaign("TestSuite.Rate_Campaign");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Rate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestSuite.Rate"));
	}

	protected Rate(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject rateMendixObject)
	{
		if (rateMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TestSuite.Rate", rateMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestSuite.Rate");

		this.rateMendixObject = rateMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Rate.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static testsuite.proxies.Rate initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testsuite.proxies.Rate.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static testsuite.proxies.Rate initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testsuite.proxies.Rate(context, mendixObject);
	}

	public static testsuite.proxies.Rate load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testsuite.proxies.Rate.initialize(context, mendixObject);
	}

	public static java.util.List<testsuite.proxies.Rate> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testsuite.proxies.Rate> result = new java.util.ArrayList<testsuite.proxies.Rate>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TestSuite.Rate" + xpathConstraint))
			result.add(testsuite.proxies.Rate.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Rating
	 */
	public final java.math.BigDecimal getRating()
	{
		return getRating(getContext());
	}

	/**
	 * @param context
	 * @return value of Rating
	 */
	public final java.math.BigDecimal getRating(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Rating.toString());
	}

	/**
	 * Set value of Rating
	 * @param rating
	 */
	public final void setRating(java.math.BigDecimal rating)
	{
		setRating(getContext(), rating);
	}

	/**
	 * Set value of Rating
	 * @param context
	 * @param rating
	 */
	public final void setRating(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal rating)
	{
		getMendixObject().setValue(context, MemberNames.Rating.toString(), rating);
	}

	/**
	 * @return value of RatingLong
	 */
	public final java.lang.Long getRatingLong()
	{
		return getRatingLong(getContext());
	}

	/**
	 * @param context
	 * @return value of RatingLong
	 */
	public final java.lang.Long getRatingLong(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.RatingLong.toString());
	}

	/**
	 * Set value of RatingLong
	 * @param ratinglong
	 */
	public final void setRatingLong(java.lang.Long ratinglong)
	{
		setRatingLong(getContext(), ratinglong);
	}

	/**
	 * Set value of RatingLong
	 * @param context
	 * @param ratinglong
	 */
	public final void setRatingLong(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long ratinglong)
	{
		getMendixObject().setValue(context, MemberNames.RatingLong.toString(), ratinglong);
	}

	/**
	 * @return value of RatingInteger
	 */
	public final java.lang.Integer getRatingInteger()
	{
		return getRatingInteger(getContext());
	}

	/**
	 * @param context
	 * @return value of RatingInteger
	 */
	public final java.lang.Integer getRatingInteger(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.RatingInteger.toString());
	}

	/**
	 * Set value of RatingInteger
	 * @param ratinginteger
	 */
	public final void setRatingInteger(java.lang.Integer ratinginteger)
	{
		setRatingInteger(getContext(), ratinginteger);
	}

	/**
	 * Set value of RatingInteger
	 * @param context
	 * @param ratinginteger
	 */
	public final void setRatingInteger(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer ratinginteger)
	{
		getMendixObject().setValue(context, MemberNames.RatingInteger.toString(), ratinginteger);
	}

	/**
	 * @return value of Rate_Campaign
	 */
	public final testsuite.proxies.Campaign getRate_Campaign() throws com.mendix.core.CoreException
	{
		return getRate_Campaign(getContext());
	}

	/**
	 * @param context
	 * @return value of Rate_Campaign
	 */
	public final testsuite.proxies.Campaign getRate_Campaign(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testsuite.proxies.Campaign result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Rate_Campaign.toString());
		if (identifier != null)
			result = testsuite.proxies.Campaign.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Rate_Campaign
	 * @param rate_campaign
	 */
	public final void setRate_Campaign(testsuite.proxies.Campaign rate_campaign)
	{
		setRate_Campaign(getContext(), rate_campaign);
	}

	/**
	 * Set value of Rate_Campaign
	 * @param context
	 * @param rate_campaign
	 */
	public final void setRate_Campaign(com.mendix.systemwideinterfaces.core.IContext context, testsuite.proxies.Campaign rate_campaign)
	{
		if (rate_campaign == null)
			getMendixObject().setValue(context, MemberNames.Rate_Campaign.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Rate_Campaign.toString(), rate_campaign.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return rateMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testsuite.proxies.Rate that = (testsuite.proxies.Rate) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestSuite.Rate";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
