// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import { CameraRoll } from "react-native";

/**
 * @param {MxObject} picture - This field is required.
 * @returns {Promise.<string>}
 */
export async function SaveToPictureLibrary(picture?: mendix.lib.MxObject): Promise<string> {
    // BEGIN USER CODE
    // Documentation https://facebook.github.io/react-native/docs/cameraroll#savetocameraroll

    if (!picture) {
        throw new TypeError("Input parameter 'Picture' is required");
    }

    if (!picture.inheritsFrom("System.FileDocument")) {
        const entity = picture.getEntity();
        throw new TypeError(`Entity ${entity} does not inherit from 'System.FileDocument'`);
    }

    const guid = picture.getGuid();
    const changedDate = picture.get("changedDate") as number;
    const url = mx.data.getDocumentUrl(guid, changedDate);

    return CameraRoll.saveToCameraRoll(url);

    // END USER CODE
}
