// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package imageviewer.proxies;

public class Container
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject containerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ImageViewer.Container";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Entity_ImageView("ImageViewer.Entity_ImageView");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Container(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ImageViewer.Container"));
	}

	protected Container(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject containerMendixObject)
	{
		if (containerMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("ImageViewer.Container", containerMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ImageViewer.Container");

		this.containerMendixObject = containerMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Container.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static imageviewer.proxies.Container initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return imageviewer.proxies.Container.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static imageviewer.proxies.Container initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new imageviewer.proxies.Container(context, mendixObject);
	}

	public static imageviewer.proxies.Container load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return imageviewer.proxies.Container.initialize(context, mendixObject);
	}

	public static java.util.List<imageviewer.proxies.Container> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<imageviewer.proxies.Container> result = new java.util.ArrayList<imageviewer.proxies.Container>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//ImageViewer.Container" + xpathConstraint))
			result.add(imageviewer.proxies.Container.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Entity_ImageView
	 */
	public final imageviewer.proxies.ImageView getEntity_ImageView() throws com.mendix.core.CoreException
	{
		return getEntity_ImageView(getContext());
	}

	/**
	 * @param context
	 * @return value of Entity_ImageView
	 */
	public final imageviewer.proxies.ImageView getEntity_ImageView(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		imageviewer.proxies.ImageView result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Entity_ImageView.toString());
		if (identifier != null)
			result = imageviewer.proxies.ImageView.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Entity_ImageView
	 * @param entity_imageview
	 */
	public final void setEntity_ImageView(imageviewer.proxies.ImageView entity_imageview)
	{
		setEntity_ImageView(getContext(), entity_imageview);
	}

	/**
	 * Set value of Entity_ImageView
	 * @param context
	 * @param entity_imageview
	 */
	public final void setEntity_ImageView(com.mendix.systemwideinterfaces.core.IContext context, imageviewer.proxies.ImageView entity_imageview)
	{
		if (entity_imageview == null)
			getMendixObject().setValue(context, MemberNames.Entity_ImageView.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Entity_ImageView.toString(), entity_imageview.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return containerMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final imageviewer.proxies.Container that = (imageviewer.proxies.Container) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ImageViewer.Container";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
