// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

/**
 * Hides a loading dialog.
 * @param {Big} identifier - This field is required.
 * @returns {boolean}
 */
// eslint-disable-next-line no-unused-vars,@typescript-eslint/no-unused-vars
function HideProgress(identifier?: BigJs.Big): boolean {
    // BEGIN USER CODE

    if (identifier == null) {
        throw new TypeError("Input parameter 'Identifier' is required");
    }

    mx.ui.hideProgress(Number(identifier));
    return true;

    // END USER CODE
}
