// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import { Clipboard } from "react-native";

/**
 * @param {string} content - This field is required.
 * @returns {Promise.<void>}
 */
export async function SetClipboardContent(content?: string): Promise<void> {
    // BEGIN USER CODE
    // Documentation https://facebook.github.io/react-native/docs/clipboard#setstring

    if (!content) {
        return Promise.reject(new Error("Input parameter 'Content' is required"));
    }

    Clipboard.setString(content);
    return Promise.resolve();

    // END USER CODE
}
