// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import ReactNative from "react-native";

/**
 * @param {MxObject} image - Required
 * @returns {string}
 */
function SaveToPhotoLibrary(image?: mendix.lib.MxObject): Promise<string> {
    // BEGIN USER CODE
    // Documentation https://facebook.github.io/react-native/docs/cameraroll#savetocameraroll

    const CameraRoll: typeof ReactNative.CameraRoll = require("react-native").CameraRoll;

    if (!image) {
        throw new TypeError("Input parameter 'image' is required");
    }

    if (!image.inheritsFrom("System.FileDocument")) {
        const entity = image.getEntity();
        throw new TypeError(`Entity ${entity} does not inherit from 'System.FileDocument'`);
    }

    const guid = image.getGuid();
    const changedDate = image.get("changedDate") as number;
    const url = mx.data.getDocumentUrl(guid, changedDate);

    return CameraRoll.saveToCameraRoll(url);

    // END USER CODE
}
