// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.

/**
 * @returns {Promise.<boolean>}
 */
export async function IsConnected(): Promise<boolean> {
    // BEGIN USER CODE
    switch (navigator.connection.type) {
        case Connection.NONE:
            return false;
        default:
            return true;
    }
    // END USER CODE
}
