// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
/**
 * @param {string} entityToRefresh - Entity which will be refreshed.
 * @returns {Promise.<void>}
 */
async function RefreshEntity(entityToRefresh) {
    // BEGIN USER CODE
    if (!entityToRefresh) {
        return Promise.reject(new Error("EntityToRefresh parameter is required"));
    }
    return new Promise(resolve => {
        mx.data.update({
            entity: entityToRefresh,
            callback: () => resolve(true)
        });
    });
    // END USER CODE
}

export { RefreshEntity };
