// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import AsyncStorage from '@react-native-community/async-storage';

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Remove a content identified by a unique key. This could be set via any of the Set Storage Item JavaScript actions
 * @param {string} key - This field is required.
 * @returns {Promise.<boolean>}
 */
export async function RemoveStorageItem(key) {
	// BEGIN USER CODE
    if (!key) {
        return Promise.reject(new Error("Input parameter 'Key' is required"));
    }
    return removeItem(key).then(() => true);
    function removeItem(key) {
        if (navigator && navigator.product === "ReactNative") {
            return AsyncStorage.removeItem(key);
        }
        if (window) {
            window.localStorage.removeItem(key);
            return Promise.resolve();
        }
        return Promise.reject(new Error("No storage API available"));
    }
	// END USER CODE
}
