import { Platform, PermissionsAndroid } from 'react-native';
import Geolocation from '@react-native-community/geolocation';

// This file was generated by Mendix Studio Pro.
/**
 * On the native platform a request for permission should be made before the `GetCurrentLocation` action would work.
 * @returns {Promise.<boolean>}
 */
async function RequestLocationPermission() {
    // BEGIN USER CODE
    if (navigator && navigator.product === "ReactNative") {
        if (!navigator.geolocation) {
            navigator.geolocation = Geolocation;
        }
        if (Platform.OS === "android") {
            const locationPermission = PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION;
            return PermissionsAndroid.check(locationPermission).then(hasPermission => hasPermission
                ? true
                : PermissionsAndroid.request(locationPermission).then(status => status === PermissionsAndroid.RESULTS.GRANTED));
        }
        else if (navigator.geolocation && navigator.geolocation.requestAuthorization) {
            try {
                navigator.geolocation.requestAuthorization();
                return Promise.resolve(true);
            }
            catch (error) {
                return Promise.reject(error);
            }
        }
    }
    return Promise.reject(new Error("No permission request for location is required for web/hybrid platform"));
    // END USER CODE
}

export { RequestLocationPermission };
