// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import { Platform, PermissionsAndroid } from 'react-native';
import Geolocation from '@react-native-community/geolocation';

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * On the native platform a request for permission should be made before the `GetCurrentLocation` action would work.
 * @returns {Promise.<boolean>}
 */
export async function RequestLocationPermission() {
	// BEGIN USER CODE
    if (navigator && navigator.product === "ReactNative") {
        if (!navigator.geolocation) {
            navigator.geolocation = Geolocation;
        }
        if (Platform.OS === "android") {
            const locationPermission = PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION;
            return PermissionsAndroid.check(locationPermission).then(hasPermission => hasPermission
                ? true
                : PermissionsAndroid.request(locationPermission).then(status => status === PermissionsAndroid.RESULTS.GRANTED));
        }
        else if (navigator.geolocation && navigator.geolocation.requestAuthorization) {
            try {
                navigator.geolocation.requestAuthorization();
                return Promise.resolve(true);
            }
            catch (error) {
                return Promise.reject(error);
            }
        }
    }
    return Promise.reject(new Error("No permission request for location is required for web/hybrid platform"));
	// END USER CODE
}
