// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Wait for number of milliseconds before continuing nanoflow execution.
 * @param {Big} delay - The number of milliseconds to wait. This field is required.
 * @returns {Promise.<void>}
 */
export async function Wait(delay) {
	// BEGIN USER CODE
    if (delay == null) {
        return Promise.reject(new Error("Input parameter 'delay' is required."));
    }
    return new Promise(resolve => {
        setTimeout(() => resolve(), Number(delay));
    });
	// END USER CODE
}
