// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<string>}
 */
export async function GetClipboardContent(): Promise<string> {
    // BEGIN USER CODE
    // Documentation https://www.npmjs.com/package/cordova-clipboard
    return new Promise(resolve => {
        if (!cordova.plugins || !cordova.plugins.clipboard) {
            throw new Error("GetClipboardContent action requires cordova-clipboard plugin to be installed in the app");
        }
        cordova.plugins.clipboard.paste(text => {
            resolve(text);
        });
    });
    // END USER CODE
}
