// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package videoplayer.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the VideoPlayer module
	public static void aCT_GetFileUrl(IContext context, videoplayer.proxies.VideoDocument _videoDocument)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("VideoDocument", _videoDocument == null ? null : _videoDocument.getMendixObject());
			Core.execute(context, "VideoPlayer.ACT_GetFileUrl", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_ResetData(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "VideoPlayer.ACT_ResetData", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_Validate_URL(IContext context, videoplayer.proxies.VideoPlayer _videoPlayer)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("VideoPlayer", _videoPlayer == null ? null : _videoPlayer.getMendixObject());
			Core.execute(context, "VideoPlayer.ACT_Validate_URL", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_VideoPlayer_SaveAndGiveFeedback(IContext context, videoplayer.proxies.VideoPlayer _videoPlayer)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("VideoPlayer", _videoPlayer == null ? null : _videoPlayer.getMendixObject());
			Core.execute(context, "VideoPlayer.ACT_VideoPlayer_SaveAndGiveFeedback", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean aS_RecreateData(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			return (java.lang.Boolean)Core.execute(context, "VideoPlayer.AS_RecreateData", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static videoplayer.proxies.VideoPlayer dSS_VideoPlayer_RetrieveData(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "VideoPlayer.DSS_VideoPlayer_RetrieveData", params);
			return result == null ? null : videoplayer.proxies.VideoPlayer.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}