dist: xenial
language: node_js
cache: npm
branches:
    only:
        - master
node_js:
  - "12.4.0"
  - "11.15.0"
  - "10.15.0"
  - "9.11.2"
  - "8.16.0"

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  on:
    tags: true
