// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
/**
 * @param {Big} duration - Android only setting. The time (in milliseconds) the device should vibrate. Set to empty to use the default value 500.
 * @returns {boolean}
 */
// eslint-disable-next-line no-unused-vars,@typescript-eslint/no-unused-vars
function Vibrate(duration: Big): boolean {
    // BEGIN USER CODE
    // Requires cordova-plugin-vibration
    if (!navigator.vibrate) {
        throw new Error("Vibrate action requires cordova-plugin-vibration to be installed in the app");
    }
    navigator.vibrate(parseInt(String(duration), 10));
    return true;
    // END USER CODE
}
