// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {Big} duration - Android only setting. The time (in milliseconds) the device should vibrate. Set to empty to use the default value 500.
 * @returns {Promise.<void>}
 */
export async function Vibrate(duration: Big): Promise<void> {
    // BEGIN USER CODE
    // Requires cordova-plugin-vibration
    if (!navigator.vibrate) {
        throw new Error("Vibrate action requires cordova-plugin-vibration to be installed in the app");
    }
    navigator.vibrate(parseInt(String(duration), 10));
    return Promise.resolve();
    // END USER CODE
}
