// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testsuite.proxies;

public class SampleData
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sampleDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestSuite.SampleData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Integer("Integer"),
		Decimal("Decimal"),
		ToggleDefaultTrue("ToggleDefaultTrue"),
		ToggleDefaultFalse("ToggleDefaultFalse"),
		ToggleOnChange("ToggleOnChange"),
		ToggleNoAccess("ToggleNoAccess"),
		ToggleReadOnly("ToggleReadOnly"),
		ToggleOnValidation("ToggleOnValidation"),
		ToggleOnChangeMf("ToggleOnChangeMf"),
		ToggleOnChangeNf("ToggleOnChangeNf");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SampleData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestSuite.SampleData"));
	}

	protected SampleData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sampleDataMendixObject)
	{
		if (sampleDataMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TestSuite.SampleData", sampleDataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestSuite.SampleData");

		this.sampleDataMendixObject = sampleDataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SampleData.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static testsuite.proxies.SampleData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testsuite.proxies.SampleData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static testsuite.proxies.SampleData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testsuite.proxies.SampleData(context, mendixObject);
	}

	public static testsuite.proxies.SampleData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testsuite.proxies.SampleData.initialize(context, mendixObject);
	}

	public static java.util.List<testsuite.proxies.SampleData> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testsuite.proxies.SampleData> result = new java.util.ArrayList<testsuite.proxies.SampleData>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TestSuite.SampleData" + xpathConstraint))
			result.add(testsuite.proxies.SampleData.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Integer
	 */
	public final java.lang.Integer getInteger()
	{
		return getInteger(getContext());
	}

	/**
	 * @param context
	 * @return value of Integer
	 */
	public final java.lang.Integer getInteger(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Integer.toString());
	}

	/**
	 * Set value of Integer
	 * @param integer
	 */
	public final void setInteger(java.lang.Integer integer)
	{
		setInteger(getContext(), integer);
	}

	/**
	 * Set value of Integer
	 * @param context
	 * @param integer
	 */
	public final void setInteger(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer integer)
	{
		getMendixObject().setValue(context, MemberNames.Integer.toString(), integer);
	}

	/**
	 * @return value of Decimal
	 */
	public final java.math.BigDecimal getDecimal()
	{
		return getDecimal(getContext());
	}

	/**
	 * @param context
	 * @return value of Decimal
	 */
	public final java.math.BigDecimal getDecimal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Decimal.toString());
	}

	/**
	 * Set value of Decimal
	 * @param decimal
	 */
	public final void setDecimal(java.math.BigDecimal decimal)
	{
		setDecimal(getContext(), decimal);
	}

	/**
	 * Set value of Decimal
	 * @param context
	 * @param decimal
	 */
	public final void setDecimal(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal decimal)
	{
		getMendixObject().setValue(context, MemberNames.Decimal.toString(), decimal);
	}

	/**
	 * @return value of ToggleDefaultTrue
	 */
	public final java.lang.Boolean getToggleDefaultTrue()
	{
		return getToggleDefaultTrue(getContext());
	}

	/**
	 * @param context
	 * @return value of ToggleDefaultTrue
	 */
	public final java.lang.Boolean getToggleDefaultTrue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ToggleDefaultTrue.toString());
	}

	/**
	 * Set value of ToggleDefaultTrue
	 * @param toggledefaulttrue
	 */
	public final void setToggleDefaultTrue(java.lang.Boolean toggledefaulttrue)
	{
		setToggleDefaultTrue(getContext(), toggledefaulttrue);
	}

	/**
	 * Set value of ToggleDefaultTrue
	 * @param context
	 * @param toggledefaulttrue
	 */
	public final void setToggleDefaultTrue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean toggledefaulttrue)
	{
		getMendixObject().setValue(context, MemberNames.ToggleDefaultTrue.toString(), toggledefaulttrue);
	}

	/**
	 * @return value of ToggleDefaultFalse
	 */
	public final java.lang.Boolean getToggleDefaultFalse()
	{
		return getToggleDefaultFalse(getContext());
	}

	/**
	 * @param context
	 * @return value of ToggleDefaultFalse
	 */
	public final java.lang.Boolean getToggleDefaultFalse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ToggleDefaultFalse.toString());
	}

	/**
	 * Set value of ToggleDefaultFalse
	 * @param toggledefaultfalse
	 */
	public final void setToggleDefaultFalse(java.lang.Boolean toggledefaultfalse)
	{
		setToggleDefaultFalse(getContext(), toggledefaultfalse);
	}

	/**
	 * Set value of ToggleDefaultFalse
	 * @param context
	 * @param toggledefaultfalse
	 */
	public final void setToggleDefaultFalse(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean toggledefaultfalse)
	{
		getMendixObject().setValue(context, MemberNames.ToggleDefaultFalse.toString(), toggledefaultfalse);
	}

	/**
	 * @return value of ToggleOnChange
	 */
	public final java.lang.Boolean getToggleOnChange()
	{
		return getToggleOnChange(getContext());
	}

	/**
	 * @param context
	 * @return value of ToggleOnChange
	 */
	public final java.lang.Boolean getToggleOnChange(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ToggleOnChange.toString());
	}

	/**
	 * Set value of ToggleOnChange
	 * @param toggleonchange
	 */
	public final void setToggleOnChange(java.lang.Boolean toggleonchange)
	{
		setToggleOnChange(getContext(), toggleonchange);
	}

	/**
	 * Set value of ToggleOnChange
	 * @param context
	 * @param toggleonchange
	 */
	public final void setToggleOnChange(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean toggleonchange)
	{
		getMendixObject().setValue(context, MemberNames.ToggleOnChange.toString(), toggleonchange);
	}

	/**
	 * @return value of ToggleNoAccess
	 */
	public final java.lang.Boolean getToggleNoAccess()
	{
		return getToggleNoAccess(getContext());
	}

	/**
	 * @param context
	 * @return value of ToggleNoAccess
	 */
	public final java.lang.Boolean getToggleNoAccess(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ToggleNoAccess.toString());
	}

	/**
	 * Set value of ToggleNoAccess
	 * @param togglenoaccess
	 */
	public final void setToggleNoAccess(java.lang.Boolean togglenoaccess)
	{
		setToggleNoAccess(getContext(), togglenoaccess);
	}

	/**
	 * Set value of ToggleNoAccess
	 * @param context
	 * @param togglenoaccess
	 */
	public final void setToggleNoAccess(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean togglenoaccess)
	{
		getMendixObject().setValue(context, MemberNames.ToggleNoAccess.toString(), togglenoaccess);
	}

	/**
	 * @return value of ToggleReadOnly
	 */
	public final java.lang.Boolean getToggleReadOnly()
	{
		return getToggleReadOnly(getContext());
	}

	/**
	 * @param context
	 * @return value of ToggleReadOnly
	 */
	public final java.lang.Boolean getToggleReadOnly(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ToggleReadOnly.toString());
	}

	/**
	 * Set value of ToggleReadOnly
	 * @param togglereadonly
	 */
	public final void setToggleReadOnly(java.lang.Boolean togglereadonly)
	{
		setToggleReadOnly(getContext(), togglereadonly);
	}

	/**
	 * Set value of ToggleReadOnly
	 * @param context
	 * @param togglereadonly
	 */
	public final void setToggleReadOnly(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean togglereadonly)
	{
		getMendixObject().setValue(context, MemberNames.ToggleReadOnly.toString(), togglereadonly);
	}

	/**
	 * @return value of ToggleOnValidation
	 */
	public final java.lang.Boolean getToggleOnValidation()
	{
		return getToggleOnValidation(getContext());
	}

	/**
	 * @param context
	 * @return value of ToggleOnValidation
	 */
	public final java.lang.Boolean getToggleOnValidation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ToggleOnValidation.toString());
	}

	/**
	 * Set value of ToggleOnValidation
	 * @param toggleonvalidation
	 */
	public final void setToggleOnValidation(java.lang.Boolean toggleonvalidation)
	{
		setToggleOnValidation(getContext(), toggleonvalidation);
	}

	/**
	 * Set value of ToggleOnValidation
	 * @param context
	 * @param toggleonvalidation
	 */
	public final void setToggleOnValidation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean toggleonvalidation)
	{
		getMendixObject().setValue(context, MemberNames.ToggleOnValidation.toString(), toggleonvalidation);
	}

	/**
	 * @return value of ToggleOnChangeMf
	 */
	public final java.lang.Boolean getToggleOnChangeMf()
	{
		return getToggleOnChangeMf(getContext());
	}

	/**
	 * @param context
	 * @return value of ToggleOnChangeMf
	 */
	public final java.lang.Boolean getToggleOnChangeMf(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ToggleOnChangeMf.toString());
	}

	/**
	 * Set value of ToggleOnChangeMf
	 * @param toggleonchangemf
	 */
	public final void setToggleOnChangeMf(java.lang.Boolean toggleonchangemf)
	{
		setToggleOnChangeMf(getContext(), toggleonchangemf);
	}

	/**
	 * Set value of ToggleOnChangeMf
	 * @param context
	 * @param toggleonchangemf
	 */
	public final void setToggleOnChangeMf(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean toggleonchangemf)
	{
		getMendixObject().setValue(context, MemberNames.ToggleOnChangeMf.toString(), toggleonchangemf);
	}

	/**
	 * @return value of ToggleOnChangeNf
	 */
	public final java.lang.Boolean getToggleOnChangeNf()
	{
		return getToggleOnChangeNf(getContext());
	}

	/**
	 * @param context
	 * @return value of ToggleOnChangeNf
	 */
	public final java.lang.Boolean getToggleOnChangeNf(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ToggleOnChangeNf.toString());
	}

	/**
	 * Set value of ToggleOnChangeNf
	 * @param toggleonchangenf
	 */
	public final void setToggleOnChangeNf(java.lang.Boolean toggleonchangenf)
	{
		setToggleOnChangeNf(getContext(), toggleonchangenf);
	}

	/**
	 * Set value of ToggleOnChangeNf
	 * @param context
	 * @param toggleonchangenf
	 */
	public final void setToggleOnChangeNf(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean toggleonchangenf)
	{
		getMendixObject().setValue(context, MemberNames.ToggleOnChangeNf.toString(), toggleonchangenf);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sampleDataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testsuite.proxies.SampleData that = (testsuite.proxies.SampleData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestSuite.SampleData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
