// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package about.actions;

import com.mendix.core.conf.Configuration;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class JA_GetMendixRuntimeVersion extends CustomJavaAction<java.lang.String>
{
	public JA_GetMendixRuntimeVersion(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String version = Configuration.RUNTIME_VERSION.toString();
		if(version == null || version == "")
		{
			return "Modeler Unversioned.";
		}
		return version;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_GetMendixRuntimeVersion";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
