// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import ReactNative from "react-native";

declare module "react-native" {
    export interface ShareStatic {
        share(
            content: ShareContent,
            options?: ShareOptions
        ): Promise<{
            action: string;
            activityType?: string;
        }>;
    }
}

/**
 * @param {string} message - The message to share. Required.
 * @param {string} title - Title of the message
 * @returns {boolean}
 */
function Share(message?: string, title?: string): Promise<boolean> {
    // BEGIN USER CODE
    // Documentation https://facebook.github.io/react-native/docs/share

    const RNShare: typeof ReactNative.Share = require("react-native").Share;

    if (!message) {
        throw new TypeError("Input parameter 'message' is required");
    }

    return RNShare.share({ message, title }).then(result => {
        if (result.action === RNShare.dismissedAction) {
            return false;
        }
        return true;
    });

    // END USER CODE
}
