// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package system.proxies;

public class Paging
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject pagingMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "System.Paging";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PageNumber("PageNumber"),
		IsSortable("IsSortable"),
		SortAttribute("SortAttribute"),
		SortAscending("SortAscending"),
		HasMoreData("HasMoreData");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Paging(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "System.Paging"));
	}

	protected Paging(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject pagingMendixObject)
	{
		if (pagingMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("System.Paging", pagingMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a System.Paging");

		this.pagingMendixObject = pagingMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Paging.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static system.proxies.Paging initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return system.proxies.Paging.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static system.proxies.Paging initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new system.proxies.Paging(context, mendixObject);
	}

	public static system.proxies.Paging load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return system.proxies.Paging.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of PageNumber
	 */
	public final java.lang.Long getPageNumber()
	{
		return getPageNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of PageNumber
	 */
	public final java.lang.Long getPageNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.PageNumber.toString());
	}

	/**
	 * Set value of PageNumber
	 * @param pagenumber
	 */
	public final void setPageNumber(java.lang.Long pagenumber)
	{
		setPageNumber(getContext(), pagenumber);
	}

	/**
	 * Set value of PageNumber
	 * @param context
	 * @param pagenumber
	 */
	public final void setPageNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long pagenumber)
	{
		getMendixObject().setValue(context, MemberNames.PageNumber.toString(), pagenumber);
	}

	/**
	 * @return value of IsSortable
	 */
	public final java.lang.Boolean getIsSortable()
	{
		return getIsSortable(getContext());
	}

	/**
	 * @param context
	 * @return value of IsSortable
	 */
	public final java.lang.Boolean getIsSortable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsSortable.toString());
	}

	/**
	 * Set value of IsSortable
	 * @param issortable
	 */
	public final void setIsSortable(java.lang.Boolean issortable)
	{
		setIsSortable(getContext(), issortable);
	}

	/**
	 * Set value of IsSortable
	 * @param context
	 * @param issortable
	 */
	public final void setIsSortable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean issortable)
	{
		getMendixObject().setValue(context, MemberNames.IsSortable.toString(), issortable);
	}

	/**
	 * @return value of SortAttribute
	 */
	public final java.lang.String getSortAttribute()
	{
		return getSortAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of SortAttribute
	 */
	public final java.lang.String getSortAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SortAttribute.toString());
	}

	/**
	 * Set value of SortAttribute
	 * @param sortattribute
	 */
	public final void setSortAttribute(java.lang.String sortattribute)
	{
		setSortAttribute(getContext(), sortattribute);
	}

	/**
	 * Set value of SortAttribute
	 * @param context
	 * @param sortattribute
	 */
	public final void setSortAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sortattribute)
	{
		getMendixObject().setValue(context, MemberNames.SortAttribute.toString(), sortattribute);
	}

	/**
	 * @return value of SortAscending
	 */
	public final java.lang.Boolean getSortAscending()
	{
		return getSortAscending(getContext());
	}

	/**
	 * @param context
	 * @return value of SortAscending
	 */
	public final java.lang.Boolean getSortAscending(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SortAscending.toString());
	}

	/**
	 * Set value of SortAscending
	 * @param sortascending
	 */
	public final void setSortAscending(java.lang.Boolean sortascending)
	{
		setSortAscending(getContext(), sortascending);
	}

	/**
	 * Set value of SortAscending
	 * @param context
	 * @param sortascending
	 */
	public final void setSortAscending(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean sortascending)
	{
		getMendixObject().setValue(context, MemberNames.SortAscending.toString(), sortascending);
	}

	/**
	 * @return value of HasMoreData
	 */
	public final java.lang.Boolean getHasMoreData()
	{
		return getHasMoreData(getContext());
	}

	/**
	 * @param context
	 * @return value of HasMoreData
	 */
	public final java.lang.Boolean getHasMoreData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasMoreData.toString());
	}

	/**
	 * Set value of HasMoreData
	 * @param hasmoredata
	 */
	public final void setHasMoreData(java.lang.Boolean hasmoredata)
	{
		setHasMoreData(getContext(), hasmoredata);
	}

	/**
	 * Set value of HasMoreData
	 * @param context
	 * @param hasmoredata
	 */
	public final void setHasMoreData(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hasmoredata)
	{
		getMendixObject().setValue(context, MemberNames.HasMoreData.toString(), hasmoredata);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return pagingMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final system.proxies.Paging that = (system.proxies.Paging) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "System.Paging";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
