// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import ReactNative from "react-native";

/**
 * @param {string} destinationAddress - This field is required.
 * @returns {boolean}
 */
function OpenMapsDirections(destinationAddress?: string): Promise<void> {
    // BEGIN USER CODE
    // Documentation https://facebook.github.io/react-native/docs/linking

    const Linking: typeof ReactNative.Linking = require("react-native").Linking;
    const Platform: typeof ReactNative.Platform = require("react-native").Platform;

    if (!destinationAddress) {
        throw new TypeError("Input parameter 'Destination address' is required");
    }

    destinationAddress = encodeURIComponent(destinationAddress);

    const url = Platform.select({
        ios: `maps://maps.apple.com/?daddr=${destinationAddress}`,
        android: `google.navigation:q=${destinationAddress}`
    });

    return Linking.openURL(url);

    // END USER CODE
}
