// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import ReactNative from "react-native";

/**
 * @param {string} url - This field is required.
 * @returns {boolean}
 */
function OpenURL(url?: string): Promise<boolean> {
    // BEGIN USER CODE
    // Documentation https://facebook.github.io/react-native/docs/linking

    const Linking: typeof ReactNative.Linking = require("react-native").Linking;

    if (!url) {
        throw new TypeError("Input parameter 'Url' is required");
    }

    return Linking.canOpenURL(url).then(supported => {
        if (!supported) {
            return false;
        }
        return Linking.openURL(url).then(() => true);
    });

    // END USER CODE
}
