// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import ReactNative from "react-native";

/**
 * @param {string} phoneNumber - Required
 * @returns {boolean}
 */
function TextPhoneNumber(phoneNumber?: string): Promise<void> {
    // BEGIN USER CODE
    // Documentation https://facebook.github.io/react-native/docs/linking

    const Linking: typeof ReactNative.Linking = require("react-native").Linking;

    if (!phoneNumber) {
        throw new TypeError("Input parameter 'phoneNumber' is required");
    }

    phoneNumber = encodeURIComponent(phoneNumber);

    return Linking.openURL(`sms:${phoneNumber}`);

    // END USER CODE
}
