// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import { Keyboard } from "react-native";

/**
 * @returns {Promise.<void>}
 */
export async function HideKeyboard(): Promise<void> {
    // BEGIN USER CODE
    // Documentation https://facebook.github.io/react-native/docs/keyboard

    Keyboard.dismiss();
    return Promise.resolve();

    // END USER CODE
}
