// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import { Vibration } from "react-native";

/**
 * @param {Big} duration - Android only setting. The time (in milliseconds) the device should vibrate. Set to empty to use the default value 500.
 * @returns {Promise.<void>}
 */
export async function Vibrate(duration?: BigJs.Big): Promise<void> {
    // BEGIN USER CODE
    // Documentation https://facebook.github.io/react-native/docs/vibration#vibrate

    const pattern = duration ? Number(duration) : 500;

    Vibration.vibrate(pattern, false);
    return Promise.resolve();

    // END USER CODE
}
