// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package system.proxies;

public class HttpResponse extends system.proxies.HttpMessage
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "System.HttpResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		StatusCode("StatusCode"),
		ReasonPhrase("ReasonPhrase"),
		HttpVersion("HttpVersion"),
		Content("Content");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public HttpResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "System.HttpResponse"));
	}

	protected HttpResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject httpResponseMendixObject)
	{
		super(context, httpResponseMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("System.HttpResponse", httpResponseMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a System.HttpResponse");
	}

	/**
	 * @deprecated Use 'HttpResponse.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static system.proxies.HttpResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return system.proxies.HttpResponse.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static system.proxies.HttpResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new system.proxies.HttpResponse(context, mendixObject);
	}

	public static system.proxies.HttpResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return system.proxies.HttpResponse.initialize(context, mendixObject);
	}

	/**
	 * @return value of StatusCode
	 */
	public final java.lang.Integer getStatusCode()
	{
		return getStatusCode(getContext());
	}

	/**
	 * @param context
	 * @return value of StatusCode
	 */
	public final java.lang.Integer getStatusCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.StatusCode.toString());
	}

	/**
	 * Set value of StatusCode
	 * @param statuscode
	 */
	public final void setStatusCode(java.lang.Integer statuscode)
	{
		setStatusCode(getContext(), statuscode);
	}

	/**
	 * Set value of StatusCode
	 * @param context
	 * @param statuscode
	 */
	public final void setStatusCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer statuscode)
	{
		getMendixObject().setValue(context, MemberNames.StatusCode.toString(), statuscode);
	}

	/**
	 * @return value of ReasonPhrase
	 */
	public final java.lang.String getReasonPhrase()
	{
		return getReasonPhrase(getContext());
	}

	/**
	 * @param context
	 * @return value of ReasonPhrase
	 */
	public final java.lang.String getReasonPhrase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReasonPhrase.toString());
	}

	/**
	 * Set value of ReasonPhrase
	 * @param reasonphrase
	 */
	public final void setReasonPhrase(java.lang.String reasonphrase)
	{
		setReasonPhrase(getContext(), reasonphrase);
	}

	/**
	 * Set value of ReasonPhrase
	 * @param context
	 * @param reasonphrase
	 */
	public final void setReasonPhrase(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reasonphrase)
	{
		getMendixObject().setValue(context, MemberNames.ReasonPhrase.toString(), reasonphrase);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final system.proxies.HttpResponse that = (system.proxies.HttpResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "System.HttpResponse";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
