// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package about.proxies;

public enum DTAPMode
{
	DEVELOPMENT(new java.lang.String[][] { new java.lang.String[] { "en_GB", "Development" }, new java.lang.String[] { "en_US", "Development" } }),
	TESTING(new java.lang.String[][] { new java.lang.String[] { "en_GB", "Testing" }, new java.lang.String[] { "en_US", "Testing" } }),
	ACCEPTANCE(new java.lang.String[][] { new java.lang.String[] { "en_GB", "Acceptance" }, new java.lang.String[] { "en_US", "Acceptance" } }),
	PRODUCTION(new java.lang.String[][] { new java.lang.String[] { "en_GB", "Production" }, new java.lang.String[] { "en_US", "Production" } }),
	TRAIL(new java.lang.String[][] { new java.lang.String[] { "en_GB", "Trial" }, new java.lang.String[] { "en_US", "Trail" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private DTAPMode(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
