sudo: required
dist: trusty
language: node_js
node_js:
- '6'
before_install:
- npm i -g npm
- npm install grunt-cli -g
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- wget -q -O - http://opensource.wandisco.com/wandisco-debian.gpg | sudo apt-key add -
- sudo sh -c "echo 'deb http://opensource.wandisco.com/debian/ wheezy svn17' > /etc/apt/sources.list.d/wandisco-subversion.list"
- sudo apt-get -qq update
- sudo apt-get install -y --allow-downgrades subversion=1.7.22-1+WANdisco libsvn1=1.7.22-1+WANdisco
- svn --version
- npm --version
after_success:
- bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - node_modules
env:
  global:
  - MX_APP_NAME=offlinesearch
  - MX_BRANCH_NAME=trunk
  - MX_PROJECT_ID=fd556f33-bbc2-4c60-bf68-a36d7f4ef872
  - MX_ENVIRONMENT=Sandbox
  - MX_USER=ci@flockofbirds.org
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_KEY
  file: dist/release/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: $TRAVIS_REPO_SLUG
    tags: true
