// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import Firebase from "react-native-firebase";

/**
 * @param {string} notificationId - This field is required.
 * @returns {void}
 */
export async function CancelScheduledNotification(notificationId?: string): Promise<void> {
    // BEGIN USER CODE

    if (!notificationId) {
        throw new TypeError("Input parameter 'Notification id' is required");
    }

    Firebase.notifications().cancelNotification(notificationId);
    return Promise.resolve();

    // END USER CODE
}
