// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import Firebase from "react-native-firebase";

/**
 * Cancels all pending scheduled notifications.
 * @returns {void}
 */
export async function CancelAllScheduledNotifications(): Promise<void> {
    // BEGIN USER CODE
    // Documentation https://rnfirebase.io/docs/v5.x.x/notifications/reference/Notifications#cancelAllNotifications

    Firebase.notifications().cancelAllNotifications();
    return Promise.resolve();

    // END USER CODE
}
