// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import Firebase from "react-native-firebase";

/**
 * This generated registration token is used to identify the app instance and periodically sends data to the backend.
 * @returns {string}
 */
export async function getPushNotificationToken(): Promise<string> {
    // BEGIN USER CODE
    // Documentation https://rnfirebase.io/docs/v5.x.x/messaging/reference/Messaging#getToken

    return Firebase.messaging().getToken();

    // END USER CODE
}
