// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import { Platform } from "react-native";
import Firebase from "react-native-firebase";

/**
 * Notification permissions are required to send a user push messages. Calling this action displays the permission dialog to the user.
 * Returns true if permission is granted, otherwise it returns false.
 * @returns {boolean}
 */
export async function RequestNotificationPermission(): Promise<boolean> {
    // BEGIN USER CODE
    // Documentation https://rnfirebase.io/docs/v5.x.x/notifications/receiving-notifications

    return Firebase.messaging()
        .requestPermission()
        .then(() =>
            Platform.OS === "ios"
                ? Firebase.messaging()
                      .ios.registerForRemoteNotifications()
                      .then(() => true)
                : true
        )
        .catch(() => false);

    // END USER CODE
}
