// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import Firebase from "react-native-firebase";

/**
 * Displays the specified notification at a future moment in time.
 *
 * Note: It is not possible to display a notification whilst the app is in the foreground on iOS 9.
 * @param {Date} date - This field is required.
 * @param {string} body - This field is required.
 * @param {string} title
 * @param {string} subtitle
 * @param {boolean} playSound
 * @param {string} notificationId - This ID can be used to cancel the scheduled notification later.
 * @param {string} actionName
 * @param {string} actionGuid
 * @returns {void}
 */
export async function ScheduleNotification(
    date?: Date,
    body?: string,
    title?: string,
    subtitle?: string,
    playSound?: boolean,
    notificationId?: string,
    actionName?: string,
    actionGuid?: string
): Promise<void> {
    // BEGIN USER CODE
    // Documentation https://rnfirebase.io/docs/v5.x.x/notifications/scheduling-notifications

    if (!date) {
        throw new TypeError("Input parameter 'Date' is required");
    }

    if (!body) {
        throw new TypeError("Input parameter 'Body' is required");
    }

    const channel = new Firebase.notifications.Android.Channel(
        "mendix-local-notifications",
        "Local notifications",
        Firebase.notifications.Android.Importance.Default
    );
    await Firebase.notifications().android.createChannel(channel);

    const notification = new Firebase.notifications.Notification()
        .setBody(body)
        .android.setChannelId("mendix-local-notifications");

    if (title) {
        notification.setTitle(title);
    }

    if (subtitle) {
        notification.setSubtitle(subtitle);
    }

    if (playSound) {
        notification.setSound("default");
    }

    if (actionName || actionGuid) {
        notification.setData({
            actionName,
            guid: actionGuid
        });
    }

    if (notificationId) {
        notification.setNotificationId(notificationId);
    }

    Firebase.notifications().scheduleNotification(notification, {
        fireDate: date.getTime()
    });

    return Promise.resolve();

    // END USER CODE
}
