// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import Firebase from "react-native-firebase";

/**
 * @param {Big} badgeNumber - This field is required. Should be greater than or equal to 0.
 * @returns {boolean}
 */
export async function SetBadgeNumber(badgeNumber?: BigJs.Big): Promise<void> {
    // BEGIN USER CODE
    // Documentation https://rnfirebase.io/docs/v5.x.x/notifications/reference/Notifications#setBadge

    if (!badgeNumber) {
        throw new TypeError("Input parameter 'Badge number' is required");
    }

    if (badgeNumber.lt(0)) {
        throw new TypeError("Input parameter 'Badge number' should be zero or greater");
    }

    Firebase.notifications().setBadge(Number(badgeNumber));
    return Promise.resolve();

    // END USER CODE
}
