// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import { Big } from "big.js";
import { Alert, Linking, NativeModules, Platform } from "react-native";
import {
    CameraOptions,
    ErrorCode,
    ImageLibraryOptions,
    ImagePickerResponse,
    launchCamera,
    launchImageLibrary
} from "react-native-image-picker";
import { getLocales } from "react-native-localize";
import { check, PERMISSIONS, request, RESULTS } from "react-native-permissions";

type PictureSource = "camera" | "imageLibrary" | "either";

type PictureQuality = "original" | "low" | "medium" | "high" | "custom";

type ImagePickerV2Response = {
    customButton: string;
    didCancel: boolean;
    error: string;
    data: string;
    uri: string;
    origURL?: string;
    isVertical: boolean;
    width: number;
    height: number;
    fileSize: number;
    type?: string;
    fileName?: string;
    path?: string;
    latitude?: number;
    longitude?: number;
    timestamp?: string;
};

type ImagePickerV2Options = {
    title?: string;
    cancelButtonTitle?: string;
    takePhotoButtonTitle?: string;
    chooseFromLibraryButtonTitle?: string;
    chooseWhichLibraryTitle?: string;
    customButtons?: Array<{
        name?: string;
        title?: string;
    }>;
    cameraType?: "front" | "back";
    mediaType?: "photo" | "video" | "mixed";
    maxWidth?: number;
    maxHeight?: number;
    quality?: number;
    videoQuality?: "low" | "medium" | "high";
    durationLimit?: number;
    rotation?: number;
    allowsEditing?: boolean;
    noData?: boolean;
    storageOptions?: {
        skipBackup?: boolean;
        path?: string;
        cameraRoll?: boolean;
        waitUntilSaved?: boolean;
        privateDirectory?: boolean;
    };
    permissionDenied?: {
        title: string;
        text: string;
        reTryTitle: string;
        okTitle: string;
    };
    tintColor?: number | string;
};

/**
 * Take a picture using the camera or import one from the image library on the device.
 *
 * When the result is true, the picture has been saved in the Picture object
 *
 * @param {MxObject} picture - This field is required.
 * @param {"NativeMobileResources.PictureSource.camera"|"NativeMobileResources.PictureSource.imageLibrary"} pictureSource - Select a picture from the library or the camera. The default is camera.
 * @param {"NativeMobileResources.PictureQuality.original"|"NativeMobileResources.PictureQuality.low"|"NativeMobileResources.PictureQuality.medium"|"NativeMobileResources.PictureQuality.high"|"NativeMobileResources.PictureQuality.custom"} pictureQuality - The default picture quality is 'Medium'.
 * @param {Big} maximumWidth - The picture will be scaled to this maximum pixel width, while maintaining the aspect ratio.
 * @param {Big} maximumHeight - The picture will be scaled to this maximum pixel height, while maintaining the aspect ratio.
 * @returns {Promise.<boolean>}
 */
export async function TakePicture(
    picture?: mendix.lib.MxObject,
    pictureSource?: PictureSource,
    pictureQuality?: PictureQuality,
    maximumWidth?: Big,
    maximumHeight?: Big
): Promise<boolean> {
    // BEGIN USER CODE
    if (!picture) {
        return Promise.reject(new Error("Input parameter 'Picture' is required"));
    }

    if (!picture.inheritsFrom("System.FileDocument")) {
        return Promise.reject(new Error(`Entity ${picture.getEntity()} does not inherit from 'System.FileDocument'`));
    }

    if (pictureQuality === "custom" && !maximumHeight && !maximumWidth) {
        return Promise.reject(
            new Error("Picture quality is set to 'Custom', but no maximum width or height was provided")
        );
    }

    // V3 dropped the feature of providing an action sheet so users can decide on which action to take, camera or library.
    const nativeVersionMajor = NativeModules.ImagePickerManager.showImagePicker ? 2 : 4;

    try {
        const uri = await takePicture();

        if (!uri) {
            return false;
        }

        return storeFile(picture, uri);
    } catch (error) {
        if (error === "canceled") {
            return false;
        }

        throw new Error(error);
    }

    function takePicture(): Promise<string | undefined> {
        return new Promise((resolve, reject) => {
            getPictureMethod()
                .then(method =>
                    method(getOptions(), (response: ImagePickerV2Response | ImagePickerResponse) => {
                        if (response.didCancel) {
                            return resolve();
                        }

                        if (nativeVersionMajor === 2) {
                            response = response as ImagePickerV2Response;

                            if (response.error) {
                                const unhandledError = handleImagePickerV2Error(response.error);

                                if (!unhandledError) {
                                    return resolve();
                                }

                                return reject(new Error(response.error));
                            }

                            return resolve(response.uri);
                        }

                        response = response as ImagePickerResponse;

                        if (response.errorCode) {
                            handleImagePickerV4Error(response.errorCode, response.errorMessage);

                            return resolve();
                        }

                        return resolve(response.assets[0].uri);
                    })
                )
                .catch(error => reject(error));
        });
    }

    function storeFile(imageObject: mendix.lib.MxObject, uri: string): Promise<boolean> {
        return new Promise((resolve, reject) => {
            fetch(uri)
                .then(response => response.blob())
                .then(blob => {
                    // eslint-disable-next-line no-useless-escape
                    const filename = /[^\/]*$/.exec(uri)![0];

                    mx.data.saveDocument(
                        imageObject.getGuid(),
                        filename,
                        {},
                        blob,
                        async () => {
                            await NativeModules.NativeFsModule.remove(uri);

                            imageObject.set("Name", filename);

                            mx.data.commit({
                                mxobj: imageObject,
                                callback: () => resolve(true),
                                error: (error: Error) => reject(error)
                            });
                        },
                        (error: Error) => {
                            NativeModules.NativeFsModule.remove(uri);

                            reject(error);
                        }
                    );
                })
                .catch(error => reject(error));
        });
    }

    async function getPictureMethod(): Promise<
        (
            options: ImagePickerV2Options | CameraOptions | ImageLibraryOptions,
            callback: (response: ImagePickerV2Response | ImagePickerResponse) => void
        ) => void
    > {
        function handleCameraRequest() {
            return async () => {
                if (Platform.OS === "android" && nativeVersionMajor === 4) {
                    await checkAndMaybeRequestAndroidPermission();
                }

                return launchCamera;
            };
        }

        switch (pictureSource) {
            case "imageLibrary":
                return () => Promise.resolve(launchImageLibrary);

            case "camera":
                return handleCameraRequest();

            // TODO: I don't see much value in this since an update to native-mobile-resources can include an edit to Enum used. Maybe remove?
            case "either":
                throw new Error(
                    "Either is no longer a supported PictureSource value. Please use `camera` or `imageLibrary`."
                ); // TODO: enduser copy

            default:
                return handleCameraRequest();
        }
    }

    async function checkAndMaybeRequestAndroidPermission() {
        let requestResult: string;

        async function requestAndroidPermission() {
            requestResult = await request(PERMISSIONS.ANDROID.CAMERA);

            if (requestResult === RESULTS.DENIED) {
                // re-enter request flow. note, if a request is denied twice, result = blocked.
                requestResult = await requestAndroidPermission();
            }

            return requestResult;
        }

        // https://github.com/zoontek/react-native-permissions#android-flow
        const statusResult = await check(PERMISSIONS.ANDROID.CAMERA);

        if (statusResult === RESULTS.UNAVAILABLE) {
            throw new Error("The camera is unavailable."); // TODO: enduser copy
        }

        if (statusResult === RESULTS.BLOCKED) {
            throw new Error("Blocked from using camera."); // TODO: enduser copy
        }

        if (statusResult === RESULTS.DENIED) {
            requestResult = await requestAndroidPermission();

            if (requestResult === RESULTS.BLOCKED) {
                throw new Error("The camera is currently blocked from use."); // TODO: enduser copy
            }
        }
    }

    function getOptions(): ImagePickerV2Options | CameraOptions | ImageLibraryOptions {
        const { maxWidth, maxHeight } = getPictureQuality();

        if (nativeVersionMajor === 2) {
            const [language] = getLocales().map(local => local.languageCode);
            const isDutch = language === "nl";

            return {
                mediaType: "photo" as const,
                maxWidth,
                maxHeight,
                noData: true,
                title: isDutch ? "Foto toevoegen" : "Select a photo",
                cancelButtonTitle: isDutch ? "Annuleren" : "Cancel",
                takePhotoButtonTitle: isDutch ? "Foto maken" : "Take photo",
                chooseFromLibraryButtonTitle: isDutch ? "Kies uit bibliotheek" : "Choose from library",
                permissionDenied: {
                    title: isDutch
                        ? "Deze app heeft geen toegang tot uw camera of foto's"
                        : "This app does not have access to your camera or photos",
                    text: isDutch
                        ? "Ga naar Instellingen > Privacy om toegang tot uw camera en bestanden te verlenen."
                        : "To enable access, tap Settings > Privacy and turn on Camera and Photos/Storage.",
                    reTryTitle: isDutch ? "Instellingen" : "Settings",
                    okTitle: isDutch ? "Annuleren" : "Cancel"
                },
                storageOptions: {
                    skipBackup: true,
                    cameraRoll: false,
                    privateDirectory: true
                }
            };
        }

        return {
            mediaType: "photo" as const,
            maxWidth,
            maxHeight
        };
    }

    function getPictureQuality(): { maxWidth: number; maxHeight: number } {
        switch (pictureQuality) {
            case "low":
                return {
                    maxWidth: 1024,
                    maxHeight: 1024
                };
            case "medium":
            default:
                return {
                    maxWidth: 2048,
                    maxHeight: 2048
                };
            case "high":
                return {
                    maxWidth: 4096,
                    maxHeight: 4096
                };
            case "custom":
                return {
                    maxWidth: Number(maximumWidth),
                    maxHeight: Number(maximumHeight)
                };
        }
    }

    function handleImagePickerV2Error(error: string): string | undefined {
        const ERRORS = {
            AndroidPermissionDenied: "Permissions weren't granted",
            iOSPhotoLibraryPermissionDenied: "Photo library permissions not granted",
            iOSCameraPermissionDenied: "Camera permissions not granted"
        };

        switch (error) {
            case ERRORS.iOSPhotoLibraryPermissionDenied:
                showAlert(
                    "This app does not have access to your photos or videos",
                    "To enable access, tap Settings and turn on Photos."
                );
                return;

            case ERRORS.iOSCameraPermissionDenied:
                showAlert(
                    "This app does not have access to your camera",
                    "To enable access, tap Settings and turn on Camera."
                );
                return;

            case ERRORS.AndroidPermissionDenied:
                // Ignore this error because the image picker plugin already shows an alert in this case.
                return;

            default:
                return error;
        }
    }

    function showAlert(title: string, message: string): void {
        Alert.alert(
            title,
            message,
            [
                { text: "Cancel", style: "cancel" },
                ...(Platform.OS === "ios"
                    ? [{ text: "Settings", onPress: () => Linking.openURL("app-settings:") }]
                    : [])
            ],
            { cancelable: false }
        );
    }

    // TODO: end-user messages/copy
    function handleImagePickerV4Error(errorCode: ErrorCode, errorMessage?: string) {
        switch (errorCode) {
            case "camera_unavailable":
                showAlert("Device camera not available", "!!!!!REPLACEME!!!!!!.");
                break;
            case "permission":
                showAlert(
                    "Access to the device camera and image library is required",
                    Platform.OS === "ios"
                        ? "To enable access, tap Settings and turn on Camera and Photos."
                        : "!!!!!REPLACEME!!!!!!."
                );
                break;
            case "others":
                showAlert("Something went wrong", `${errorMessage}.` ?? "!!!!!REPLACEME!!!!!!.");
                break;
            default:
                showAlert("Something went wrong", "!!!!!REPLACEME!!!!!!.");
                break;
        }
    }

    // END USER CODE
}
