// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

/**
 * @param {MxObject[]} list - This field is required.
 * @returns {string}
 */
function CountList(list?: mendix.lib.MxObject[]): number {
    // BEGIN USER CODE

    if (!list) {
        throw new TypeError("Input parameter 'List' is required");
    }

    return list.length;

    // END USER CODE
}
