import { ActionButtonType } from "../../types/widgets";
export declare const btnSecondary: ActionButtonType;
export declare const btnSuccess: ActionButtonType;
export declare const btnWarning: ActionButtonType;
export declare const btnDanger: ActionButtonType;
export declare const btnPrimaryInversed: ActionButtonType;
export declare const btnSecondaryInversed: ActionButtonType;
export declare const btnIconPrimary: ActionButtonType;
export declare const btnIconSecondary: ActionButtonType;
export declare const btnIconSuccess: ActionButtonType;
export declare const btnIconWarning: ActionButtonType;
export declare const btnIconDanger: ActionButtonType;
export declare const btnIconWhite: ActionButtonType;
export declare const btnIconGrayRounded: ActionButtonType;
export declare const btnIconPrimaryBackground: ActionButtonType;
export declare const btnAsText: ActionButtonType;
export declare const btnLarge: ActionButtonType;
