import { Helperclass } from "../../types/helperclass";
export declare const hideOnAndroid: Helperclass;
export declare const hideOnIos: Helperclass;
export declare const backgroundPrimary: Helperclass;
export declare const backgroundSecondary: Helperclass;
export declare const backgroundBrandPrimary: Helperclass;
export declare const backgroundBrandSuccess: Helperclass;
export declare const backgroundBrandWarning: Helperclass;
export declare const backgroundBrandDanger: Helperclass;
export declare const backgroundGray: Helperclass;
export declare const borderTop: Helperclass;
export declare const borderBottom: Helperclass;
