// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package videoplayer.proxies;

public class VideoDocument extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "VideoPlayer.VideoDocument";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ViewUrl("ViewUrl"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public VideoDocument(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "VideoPlayer.VideoDocument"));
	}

	protected VideoDocument(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject videoDocumentMendixObject)
	{
		super(context, videoDocumentMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("VideoPlayer.VideoDocument", videoDocumentMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a VideoPlayer.VideoDocument");
	}

	/**
	 * @deprecated Use 'VideoDocument.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static videoplayer.proxies.VideoDocument initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return videoplayer.proxies.VideoDocument.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static videoplayer.proxies.VideoDocument initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new videoplayer.proxies.VideoDocument(context, mendixObject);
	}

	public static videoplayer.proxies.VideoDocument load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return videoplayer.proxies.VideoDocument.initialize(context, mendixObject);
	}

	public static java.util.List<videoplayer.proxies.VideoDocument> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<videoplayer.proxies.VideoDocument> result = new java.util.ArrayList<videoplayer.proxies.VideoDocument>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//VideoPlayer.VideoDocument" + xpathConstraint))
			result.add(videoplayer.proxies.VideoDocument.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of ViewUrl
	 */
	public final java.lang.String getViewUrl()
	{
		return getViewUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of ViewUrl
	 */
	public final java.lang.String getViewUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ViewUrl.toString());
	}

	/**
	 * Set value of ViewUrl
	 * @param viewurl
	 */
	public final void setViewUrl(java.lang.String viewurl)
	{
		setViewUrl(getContext(), viewurl);
	}

	/**
	 * Set value of ViewUrl
	 * @param context
	 * @param viewurl
	 */
	public final void setViewUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String viewurl)
	{
		getMendixObject().setValue(context, MemberNames.ViewUrl.toString(), viewurl);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final videoplayer.proxies.VideoDocument that = (videoplayer.proxies.VideoDocument) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "VideoPlayer.VideoDocument";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
