import TouchID from 'react-native-touch-id';

// This file was generated by Mendix Modeler.
/**
 * @param {string} reason - The reason for requesting authentication. If empty, the system default message is used.
 * @returns {Promise.<boolean>}
 */
async function BiometricAuthentication(reason) {
    // BEGIN USER CODE
    // Documentation https://github.com/naoufal/react-native-touch-id
    return TouchID.authenticate(reason)
        .then(() => true)
        .catch(() => false);
    // END USER CODE
}

export { BiometricAuthentication };
