import { Platform, NativeModules } from 'react-native';
import PushNotification from 'react-native-push-notification';

// This file was generated by Mendix Modeler.
/**
 * Cancels all pending scheduled notifications.
 * @returns {Promise.<void>}
 */
async function CancelAllScheduledNotifications() {
    // BEGIN USER CODE
    // Documentation https://github.com/zo0r/react-native-push-notification
    const isIOS = Platform.OS === "ios";
    if (NativeModules &&
        ((isIOS && !NativeModules.RNCPushNotificationIOS) || (!isIOS && !NativeModules.RNPushNotification))) {
        return Promise.reject(new Error("Notifications module is not available in your app"));
    }
    PushNotification.cancelAllLocalNotifications();
    return Promise.resolve();
    // END USER CODE
}

export { CancelAllScheduledNotifications };
