import { NativeModules } from 'react-native';
import messaging from '@react-native-firebase/messaging';

// This file was generated by Mendix Modeler.
/**
 * This generated registration token is used to identify the app instance and periodically sends data to the backend.
 * @returns {Promise.<string>}
 */
async function getPushNotificationToken() {
    // BEGIN USER CODE
    // Documentation https://rnfirebase.io/docs/v5.x.x/messaging/reference/Messaging#getToken
    if (NativeModules && !NativeModules.RNFBMessagingModule) {
        return Promise.reject(new Error("Firebase module is not available in your app"));
    }
    return messaging().getToken();
    // END USER CODE
}

export { getPushNotificationToken };
