import { NativeModules } from 'react-native';

// This file was generated by Mendix Modeler.
/**
 * Checks if the user has granted the appropriate permissions to be able to send and receive messages.
 * Returns true if permission is granted, false otherwise.
 * @returns {Promise.<boolean>}
 */
async function HasNotificationPermission() {
    // BEGIN USER CODE
    // Documentation https://rnfirebase.io/docs/v5.x.x/notifications/receiving-notifications
    if (NativeModules && !NativeModules.RNFBMessagingModule) {
        return Promise.reject(new Error("Firebase module is not available in your app"));
    }
    return NativeModules.RNFBMessagingModule.hasPermission().then((authStatus) => {
        if (authStatus) {
            return Promise.resolve(true);
        }
        else {
            return Promise.resolve(false);
        }
    });
    // END USER CODE
}

export { HasNotificationPermission };
