import { Keyboard } from 'react-native';

// This file was generated by Mendix Modeler.
/**
 * @returns {Promise.<void>}
 */
async function HideKeyboard() {
    // BEGIN USER CODE
    // Documentation https://facebook.github.io/react-native/docs/keyboard
    Keyboard.dismiss();
    return Promise.resolve();
    // END USER CODE
}

export { HideKeyboard };
