import { saveToCameraRoll } from '@react-native-community/cameraroll';

// This file was generated by Mendix Modeler.
/**
 * @param {MxObject} picture - This field is required.
 * @returns {Promise.<string>}
 */
async function SaveToPictureLibrary(picture) {
    // BEGIN USER CODE
    // Documentation https://facebook.github.io/react-native/docs/cameraroll#savetocameraroll
    if (!picture) {
        return Promise.reject(new Error("Input parameter 'Picture' is required"));
    }
    if (!picture.inheritsFrom("System.FileDocument")) {
        const entity = picture.getEntity();
        return Promise.reject(new Error(`Entity ${entity} does not inherit from 'System.FileDocument'`));
    }
    const guid = picture.getGuid();
    const changedDate = picture.get("changedDate");
    const url = mx.data.getDocumentUrl(guid, changedDate);
    return saveToCameraRoll(url);
    // END USER CODE
}

export { SaveToPictureLibrary };
