// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Scroll the window to make targeted element visible
 * @param {string} targetSelector
 * @returns {Promise.<void>}
 */
export async function ScrollTo(targetSelector: string): Promise<void> {
    // BEGIN USER CODE
    const element = document.querySelector(targetSelector);
    if (element) {
        element.scrollIntoView({
            behavior: "smooth",
            block: "start",
            inline: "nearest"
        });
    } else {
        console.log("no item found");
    }
    // END USER CODE
}
