// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import AddCalendarEventLib from "react-native-add-calendar-event";

// eslint-disable-next-line no-unused-vars,@typescript-eslint/no-unused-vars
function EditCalendarEvent(eventId?: string): Promise<boolean> {
    // BEGIN USER CODE
    // Documentation https://github.com/vonovak/react-native-add-calendar-event#editing-an-event

    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const AddCalendarEvent: typeof AddCalendarEventLib = require("react-native-add-calendar-event");

    if (!eventId) {
        throw new TypeError("Input parameter 'Event id' is required");
    }

    return AddCalendarEvent.presentEventEditingDialog({
        eventId
    }).then(() => true);

    // END USER CODE
}
