dist: xenial
language: node_js
cache: npm
branches:
    only:
        - master

jobs:
    include:
        - name: "Lint"
          script: npm run lint
        - name: "Build"
          script: npm run build
