// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

/**
 * @param {string} entity
 * @param {MxObject} entityObject
 * @returns {string}
 */
function GetGuid(entity: string, entityObject: mendix.lib.MxObject): string {
    // BEGIN USER CODE
    if (!entity) {
        throw new TypeError("Input parameter 'Entity' is required.");
    }

    if (!entityObject) {
        throw new TypeError("Input parameter 'Entity object' is required.");
    }

    return entityObject.getGuid();
    // END USER CODE
}
