// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

/**
 * @param {MxObject} entity
 * @returns {string}
 */
function GetGuid(entity: mendix.lib.MxObject): string {
    // BEGIN USER CODE
    return entity.getGuid();
    // END USER CODE
}
