// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

/**
 * @param {MxObject} entity
 * @returns {string}
 */
function Wait(delay?: BigJs.Big): Promise<void> {
    // BEGIN USER CODE
    if (delay == null) {
        throw new TypeError("Input parameter 'delay' is required.");
    }

    return new Promise(resolve => {
        setTimeout(() => resolve(), Number(delay));
    });
    // END USER CODE
}
