// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package about.proxies;

public class About
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject aboutMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "About.About";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ModelVersion("ModelVersion"),
		LastUpdate("LastUpdate"),
		ServerIP("ServerIP"),
		MendixVersion("MendixVersion"),
		ApplicationURL("ApplicationURL"),
		DTAPMode("DTAPMode");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public About(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "About.About"));
	}

	protected About(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject aboutMendixObject)
	{
		if (aboutMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("About.About", aboutMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a About.About");

		this.aboutMendixObject = aboutMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'About.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static about.proxies.About initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return about.proxies.About.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static about.proxies.About initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new about.proxies.About(context, mendixObject);
	}

	public static about.proxies.About load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return about.proxies.About.initialize(context, mendixObject);
	}

	public static java.util.List<about.proxies.About> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<about.proxies.About> result = new java.util.ArrayList<about.proxies.About>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//About.About" + xpathConstraint))
			result.add(about.proxies.About.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ModelVersion
	 */
	public final java.lang.String getModelVersion()
	{
		return getModelVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of ModelVersion
	 */
	public final java.lang.String getModelVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ModelVersion.toString());
	}

	/**
	 * Set value of ModelVersion
	 * @param modelversion
	 */
	public final void setModelVersion(java.lang.String modelversion)
	{
		setModelVersion(getContext(), modelversion);
	}

	/**
	 * Set value of ModelVersion
	 * @param context
	 * @param modelversion
	 */
	public final void setModelVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String modelversion)
	{
		getMendixObject().setValue(context, MemberNames.ModelVersion.toString(), modelversion);
	}

	/**
	 * @return value of LastUpdate
	 */
	public final java.util.Date getLastUpdate()
	{
		return getLastUpdate(getContext());
	}

	/**
	 * @param context
	 * @return value of LastUpdate
	 */
	public final java.util.Date getLastUpdate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastUpdate.toString());
	}

	/**
	 * Set value of LastUpdate
	 * @param lastupdate
	 */
	public final void setLastUpdate(java.util.Date lastupdate)
	{
		setLastUpdate(getContext(), lastupdate);
	}

	/**
	 * Set value of LastUpdate
	 * @param context
	 * @param lastupdate
	 */
	public final void setLastUpdate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastupdate)
	{
		getMendixObject().setValue(context, MemberNames.LastUpdate.toString(), lastupdate);
	}

	/**
	 * @return value of ServerIP
	 */
	public final java.lang.String getServerIP()
	{
		return getServerIP(getContext());
	}

	/**
	 * @param context
	 * @return value of ServerIP
	 */
	public final java.lang.String getServerIP(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ServerIP.toString());
	}

	/**
	 * Set value of ServerIP
	 * @param serverip
	 */
	public final void setServerIP(java.lang.String serverip)
	{
		setServerIP(getContext(), serverip);
	}

	/**
	 * Set value of ServerIP
	 * @param context
	 * @param serverip
	 */
	public final void setServerIP(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String serverip)
	{
		getMendixObject().setValue(context, MemberNames.ServerIP.toString(), serverip);
	}

	/**
	 * @return value of MendixVersion
	 */
	public final java.lang.String getMendixVersion()
	{
		return getMendixVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of MendixVersion
	 */
	public final java.lang.String getMendixVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MendixVersion.toString());
	}

	/**
	 * Set value of MendixVersion
	 * @param mendixversion
	 */
	public final void setMendixVersion(java.lang.String mendixversion)
	{
		setMendixVersion(getContext(), mendixversion);
	}

	/**
	 * Set value of MendixVersion
	 * @param context
	 * @param mendixversion
	 */
	public final void setMendixVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mendixversion)
	{
		getMendixObject().setValue(context, MemberNames.MendixVersion.toString(), mendixversion);
	}

	/**
	 * @return value of ApplicationURL
	 */
	public final java.lang.String getApplicationURL()
	{
		return getApplicationURL(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplicationURL
	 */
	public final java.lang.String getApplicationURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ApplicationURL.toString());
	}

	/**
	 * Set value of ApplicationURL
	 * @param applicationurl
	 */
	public final void setApplicationURL(java.lang.String applicationurl)
	{
		setApplicationURL(getContext(), applicationurl);
	}

	/**
	 * Set value of ApplicationURL
	 * @param context
	 * @param applicationurl
	 */
	public final void setApplicationURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String applicationurl)
	{
		getMendixObject().setValue(context, MemberNames.ApplicationURL.toString(), applicationurl);
	}

	/**
	 * Set value of DTAPMode
	 * @param dtapmode
	 */
	public final about.proxies.DTAPMode getDTAPMode()
	{
		return getDTAPMode(getContext());
	}

	/**
	 * @param context
	 * @return value of DTAPMode
	 */
	public final about.proxies.DTAPMode getDTAPMode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.DTAPMode.toString());
		if (obj == null)
			return null;

		return about.proxies.DTAPMode.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of DTAPMode
	 * @param dtapmode
	 */
	public final void setDTAPMode(about.proxies.DTAPMode dtapmode)
	{
		setDTAPMode(getContext(), dtapmode);
	}

	/**
	 * Set value of DTAPMode
	 * @param context
	 * @param dtapmode
	 */
	public final void setDTAPMode(com.mendix.systemwideinterfaces.core.IContext context, about.proxies.DTAPMode dtapmode)
	{
		if (dtapmode != null)
			getMendixObject().setValue(context, MemberNames.DTAPMode.toString(), dtapmode.toString());
		else
			getMendixObject().setValue(context, MemberNames.DTAPMode.toString(), null);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return aboutMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final about.proxies.About that = (about.proxies.About) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "About.About";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
