import { Helperclass } from "../../types/helperclass";
import { LayoutGridType } from "../../types/widgets";
export declare const LayoutGrid: LayoutGridType;
export declare const row: Helperclass;
export declare const col: Helperclass;
export declare const colFitToContent: Helperclass;
export declare const col1: Helperclass;
export declare const col2: Helperclass;
export declare const col3: Helperclass;
export declare const col4: Helperclass;
export declare const col5: Helperclass;
export declare const col6: Helperclass;
export declare const col7: Helperclass;
export declare const col8: Helperclass;
export declare const col9: Helperclass;
export declare const col10: Helperclass;
export declare const col11: Helperclass;
export declare const col12: Helperclass;
export declare const noGutters: Helperclass;
export declare const noGuttersRow: Helperclass;
