import { VariablesBackground, VariablesBadge, VariablesBorder, VariablesBrand, VariablesButton, VariablesContrast, VariablesFont, VariablesInput, VariablesLayoutgrid, VariablesListView, VariablesNavigation, VariablesSpacing, VariablesTabContainer } from "../types/variables";
export declare const deviceHeight: number;
export declare const deviceWidth: number;
declare let brand: VariablesBrand;
declare let background: VariablesBackground;
declare let contrast: VariablesContrast;
declare let border: VariablesBorder;
declare let font: VariablesFont;
declare let spacing: VariablesSpacing;
declare let button: VariablesButton;
declare let input: VariablesInput;
declare let navigation: VariablesNavigation;
declare let tabContainer: VariablesTabContainer;
declare let listView: VariablesListView;
declare let layoutGrid: VariablesLayoutgrid;
declare let badge: VariablesBadge;
export { brand, background, border, contrast, font, spacing, button, input, navigation, tabContainer, listView, layoutGrid, badge, };
