// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import ReactNativeFirebase from "react-native-firebase";

/**
 * Cancels all pending scheduled notifications.
 * @returns {string}
 */
function CancelAllScheduledNotifications(): void {
    // BEGIN USER CODE
    // Documentation https://rnfirebase.io/docs/v5.x.x/notifications/reference/Notifications#cancelAllNotifications

    const firebase: typeof ReactNativeFirebase = require("react-native-firebase");

    firebase.notifications().cancelAllNotifications();

    // END USER CODE
}
