// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import PushNotificationLib from "react-native-push-notification";

function CancelAndClearAllNotifications(): Promise<void> {
    // BEGIN USER CODE
    // Documentation https://github.com/zo0r/react-native-push-notification

    const PushNotification: typeof PushNotificationLib = require("react-native-push-notification");

    PushNotification.cancelAllLocalNotifications();
    return Promise.resolve();

    // END USER CODE
}
