// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import PushNotificationLib from "react-native-push-notification";

function GetPushNotificationsToken(androidSenderID?: string, requestPermissionNow?: boolean): Promise<string> {
    // BEGIN USER CODE
    // Documentation https://github.com/zo0r/react-native-push-notification

    const PushNotification: typeof PushNotificationLib = require("react-native-push-notification");

    return new Promise(resolve => {
        PushNotification.configure({
            onRegister,
            senderID: androidSenderID,
            requestPermissions: requestPermissionNow
        });

        function onRegister(token: { os: string; token: string }): void {
            resolve(token.token);
        }
    });

    // END USER CODE
}
