// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import PushNotificationLib from "react-native-push-notification";

function ScheduleNotification(
    date?: Date,
    title?: string,
    message?: string,
    playSound?: boolean,
    badgeNumber?: BigJs.Big
): Promise<void> {
    // BEGIN USER CODE
    // Documentation https://github.com/zo0r/react-native-push-notification

    const PushNotification: typeof PushNotificationLib = require("react-native-push-notification");

    if (!date) {
        throw new TypeError("Input parameter 'date' is required");
    }

    if (!message) {
        throw new TypeError("Input parameter 'message' is required");
    }

    if (badgeNumber && badgeNumber.lte(0)) {
        throw new TypeError("Input parameter 'badgeNumber' should be greater than zero");
    }

    PushNotification.localNotificationSchedule({
        date,
        title,
        message,
        playSound,
        number: badgeNumber && badgeNumber.toFixed(0)
    });
    return Promise.resolve();

    // END USER CODE
}
