// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import PushNotificationLib from "react-native-push-notification";

function SetBadgeNumber(badgeNumber?: BigJs.Big): Promise<void> {
    // BEGIN USER CODE
    // Documentation https://github.com/zo0r/react-native-push-notification#set-application-badge-icon

    const PushNotification: typeof PushNotificationLib = require("react-native-push-notification");

    if (!badgeNumber) {
        throw new TypeError("Input parameter 'badgeNumber' is required");
    }

    if (badgeNumber.lt(0)) {
        throw new TypeError("Input parameter 'badgeNumber' should be zero or greater");
    }

    const badgeNumberValue = Number(badgeNumber.toFixed(0));

    PushNotification.setApplicationIconBadgeNumber(badgeNumberValue);
    return Promise.resolve();

    // END USER CODE
}
