// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

/**
 * Wait for number of milliseconds before continuing nanoflow execution.
 * @param {Big} delay - The number of milliseconds to wait. This field is required.
 * @returns {Promise.<void>}
 */
// eslint-disable-next-line no-unused-vars,@typescript-eslint/no-unused-vars
function Wait(delay?: BigJs.Big): Promise<void> {
    // BEGIN USER CODE
    if (delay == null) {
        return Promise.reject(new TypeError("Input parameter 'delay' is required."));
    }

    return new Promise(resolve => {
        setTimeout(() => resolve(), Number(delay));
    });
    // END USER CODE
}
