// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import ReactNative from "react-native";

/**
 * @param {string} title - Required
 * @param {string} message
 * @returns {boolean}
 */
function ShowAlert(title?: string, message?: string): Promise<void> {
    // BEGIN USER CODE
    // Documentation https://facebook.github.io/react-native/docs/alert

    const RNAlert: typeof ReactNative.Alert = require("react-native").Alert;

    if (!title) {
        throw new TypeError("Input parameter 'title' is required");
    }

    RNAlert.alert(title, message);
    return Promise.resolve();

    // END USER CODE
}
