// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import ReactNative from "react-native";

/**
 * @param {string} title - This field is required.
 * @param {string} message
 * @param {string} cancelText - The default text is 'Cancel'.
 * @param {string} okText - The default text is 'OK'.
 * @returns {boolean}
 */
function ShowConfirmation(title?: string, message?: string, cancelText?: string, okText?: string): Promise<boolean> {
    // BEGIN USER CODE
    // Documentation https://facebook.github.io/react-native/docs/alert

    const Alert: typeof ReactNative.Alert = require("react-native").Alert;

    if (!title) {
        throw new TypeError("Input parameter 'Title' is required");
    }

    cancelText = cancelText || "Cancel";
    okText = okText || "OK";

    return new Promise(resolve => {
        Alert.alert(title, message, [
            { text: cancelText, onPress: () => resolve(false), style: "cancel" },
            { text: okText, onPress: () => resolve(true) }
        ]);
    });

    // END USER CODE
}
