// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {MxObject} file
 * @returns {Promise.<string>}
 */
export async function GetUrl(file) {
    // BEGIN USER CODE
    var guid = file.getGuid();
    var changedDate = file.get("changedDate");
    return mx.data.getDocumentUrl(guid, changedDate);
    // END USER CODE
}
