// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * On the native platform a request for permission should be made before the `GetCurrentLocation` action would work.
 * @returns {Promise.<boolean>}
 */
export async function RequestLocationPermission() {
    // BEGIN USER CODE
    if (navigator && navigator.product === "ReactNative") {
        var RN = require("react-native");
        if (RN.Platform.OS === "android") {
            var locationPermission = RN.PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION;
            return RN.PermissionsAndroid.check(locationPermission).then(function(hasPermission) {
                return hasPermission
                    ? true
                    : RN.PermissionsAndroid.request(locationPermission).then(function(status) {
                          return status === RN.PermissionsAndroid.RESULTS.GRANTED;
                      });
            });
        } else if (navigator.geolocation && navigator.geolocation.requestAuthorization) {
            navigator.geolocation.requestAuthorization();
        }
    }
    return Promise.resolve(true);
    // END USER CODE
}
