// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import { PermissionsAndroid, Platform } from "react-native";
import Geolocation, { GeolocationStatic } from "@react-native-community/geolocation";

/**
 * On the native platform a request for permission should be made before the `GetCurrentLocation` action would work.
 * @returns {Promise.<boolean>}
 */
export async function RequestLocationPermission(): Promise<boolean> {
    // BEGIN USER CODE

    if (navigator && navigator.product === "ReactNative") {
        if (!navigator.geolocation) {
            (navigator.geolocation as GeolocationStatic) = Geolocation;
        }

        if (Platform.OS === "android") {
            const locationPermission = PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION;

            return PermissionsAndroid.check(locationPermission).then(hasPermission =>
                hasPermission
                    ? true
                    : PermissionsAndroid.request(locationPermission).then(
                          status => status === PermissionsAndroid.RESULTS.GRANTED
                      )
            );
        } else if (navigator.geolocation && (navigator.geolocation as GeolocationStatic).requestAuthorization) {
            try {
                (navigator.geolocation as GeolocationStatic).requestAuthorization();
                return Promise.resolve(true);
            } catch (error) {
                return Promise.reject(error);
            }
        }
    }

    return Promise.reject(new Error("No permission request for location is required for web/hybrid platform"));

    // END USER CODE
}
