// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
/**
 * @returns {Promise.<void>}
 */
export async function reload(): Promise<void> {
    // BEGIN USER CODE
    mx.reload();
    return new Promise(() => {
        /** never resolve **/
    });
    // END USER CODE
}
