// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {Date} inputDate
 * @param {Big} numberOfMilliseconds
 * @returns {Promise.<Date>}
 */
export async function AddMilliseconds(inputDate: Date, numberOfMilliseconds: Big): Promise<Date> {
    // BEGIN USER CODE

    if (!inputDate) {
        throw new Error("JS_AddMilliseconds - inputDate is required");
    }

    if (!numberOfMilliseconds && numberOfMilliseconds !== 0) {
        throw new Error("JS_AddMilliseconds - numberOfMilliseconds is required");
    }

    const output = new Date(inputDate.getTime() + numberOfMilliseconds.toNumber());

    return output;

    // END USER CODE
}
