export function add(opt?: any): any;
export function addRemote(remote: any, url: any, opt: any, cb: any): any;
export function addSubmodule(url: any, name: any, opt: any, cb: any): any;
export function branch(branch: any, opt: any, cb: any): any;
export function catFile(opt: any): any;
export function checkout(branch: any, opt: any, cb: any): void;
export function checkoutFiles(opt: any): any;
export function clean(paths: any, opt: any, cb: any): any;
export function clone(remote: any, opt: any, cb: any): any;
export function commit(message: any, opt: any): any;
export function diff(compare: any, opt: any): any;
export function exec(opt: any, cb: any): any;
export function fetch(remote: any, branch: any, opt: any, cb: any): any;
export function init(opt: any, cb: any): any;
export function merge(branch: any, opt: any, cb: any): any;
export function pull(remote: any, branch: any, opt: any, cb: any): any;
export function push(remote: any, branch: any, opt: any, cb: any): any;
export function removeRemote(remote: any, opt: any, cb: any): any;
export function reset(commit: any, opt: any, cb: any): any;
export function revParse(opt: any, cb: any): any;
export function rm(opt: any): any;
export function stash(opt: any, cb: any): void;
export function status(opt: any, cb: any): any;
export function tag(version: any, message: any, opt: any, cb: any): any;
export function updateSubmodule(opt: any, cb: any): any;
