// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package progresbar.proxies;

public enum bootstrapStyle
{
	info(new java.lang.String[][] { new java.lang.String[] { "en_US", "info" } }),
	danger(new java.lang.String[][] { new java.lang.String[] { "en_US", "danger" } }),
	warning(new java.lang.String[][] { new java.lang.String[] { "en_US", "warning" } }),
	success(new java.lang.String[][] { new java.lang.String[] { "en_US", "success" } }),
	primary(new java.lang.String[][] { new java.lang.String[] { "en_US", "primary" } }),
	inverse(new java.lang.String[][] { new java.lang.String[] { "en_US", "inverse" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private bootstrapStyle(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
