// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package progresbar.proxies;

public class Progress
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject progressMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ProgresBar.Progress";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Progress("Progress"),
		BootstrapStyle("BootstrapStyle"),
		maximumValue("maximumValue"),
		Progress_Decimal("Progress_Decimal"),
		Progress_Long("Progress_Long"),
		DisplayText("DisplayText"),
		Progress_Entity("ProgresBar.Progress_Entity");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Progress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ProgresBar.Progress"));
	}

	protected Progress(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject progressMendixObject)
	{
		if (progressMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("ProgresBar.Progress", progressMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ProgresBar.Progress");

		this.progressMendixObject = progressMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Progress.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static progresbar.proxies.Progress initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return progresbar.proxies.Progress.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static progresbar.proxies.Progress initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new progresbar.proxies.Progress(context, mendixObject);
	}

	public static progresbar.proxies.Progress load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return progresbar.proxies.Progress.initialize(context, mendixObject);
	}

	public static java.util.List<progresbar.proxies.Progress> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<progresbar.proxies.Progress> result = new java.util.ArrayList<progresbar.proxies.Progress>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//ProgresBar.Progress" + xpathConstraint))
			result.add(progresbar.proxies.Progress.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Progress
	 */
	public final java.lang.Integer getProgress()
	{
		return getProgress(getContext());
	}

	/**
	 * @param context
	 * @return value of Progress
	 */
	public final java.lang.Integer getProgress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Progress.toString());
	}

	/**
	 * Set value of Progress
	 * @param progress
	 */
	public final void setProgress(java.lang.Integer progress)
	{
		setProgress(getContext(), progress);
	}

	/**
	 * Set value of Progress
	 * @param context
	 * @param progress
	 */
	public final void setProgress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer progress)
	{
		getMendixObject().setValue(context, MemberNames.Progress.toString(), progress);
	}

	/**
	 * Set value of BootstrapStyle
	 * @param bootstrapstyle
	 */
	public final progresbar.proxies.bootstrapStyle getBootstrapStyle()
	{
		return getBootstrapStyle(getContext());
	}

	/**
	 * @param context
	 * @return value of BootstrapStyle
	 */
	public final progresbar.proxies.bootstrapStyle getBootstrapStyle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.BootstrapStyle.toString());
		if (obj == null)
			return null;

		return progresbar.proxies.bootstrapStyle.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of BootstrapStyle
	 * @param bootstrapstyle
	 */
	public final void setBootstrapStyle(progresbar.proxies.bootstrapStyle bootstrapstyle)
	{
		setBootstrapStyle(getContext(), bootstrapstyle);
	}

	/**
	 * Set value of BootstrapStyle
	 * @param context
	 * @param bootstrapstyle
	 */
	public final void setBootstrapStyle(com.mendix.systemwideinterfaces.core.IContext context, progresbar.proxies.bootstrapStyle bootstrapstyle)
	{
		if (bootstrapstyle != null)
			getMendixObject().setValue(context, MemberNames.BootstrapStyle.toString(), bootstrapstyle.toString());
		else
			getMendixObject().setValue(context, MemberNames.BootstrapStyle.toString(), null);
	}

	/**
	 * @return value of maximumValue
	 */
	public final java.lang.Integer getmaximumValue()
	{
		return getmaximumValue(getContext());
	}

	/**
	 * @param context
	 * @return value of maximumValue
	 */
	public final java.lang.Integer getmaximumValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.maximumValue.toString());
	}

	/**
	 * Set value of maximumValue
	 * @param maximumvalue
	 */
	public final void setmaximumValue(java.lang.Integer maximumvalue)
	{
		setmaximumValue(getContext(), maximumvalue);
	}

	/**
	 * Set value of maximumValue
	 * @param context
	 * @param maximumvalue
	 */
	public final void setmaximumValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maximumvalue)
	{
		getMendixObject().setValue(context, MemberNames.maximumValue.toString(), maximumvalue);
	}

	/**
	 * @return value of Progress_Decimal
	 */
	public final java.math.BigDecimal getProgress_Decimal()
	{
		return getProgress_Decimal(getContext());
	}

	/**
	 * @param context
	 * @return value of Progress_Decimal
	 */
	public final java.math.BigDecimal getProgress_Decimal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Progress_Decimal.toString());
	}

	/**
	 * Set value of Progress_Decimal
	 * @param progress_decimal
	 */
	public final void setProgress_Decimal(java.math.BigDecimal progress_decimal)
	{
		setProgress_Decimal(getContext(), progress_decimal);
	}

	/**
	 * Set value of Progress_Decimal
	 * @param context
	 * @param progress_decimal
	 */
	public final void setProgress_Decimal(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal progress_decimal)
	{
		getMendixObject().setValue(context, MemberNames.Progress_Decimal.toString(), progress_decimal);
	}

	/**
	 * @return value of Progress_Long
	 */
	public final java.lang.Long getProgress_Long()
	{
		return getProgress_Long(getContext());
	}

	/**
	 * @param context
	 * @return value of Progress_Long
	 */
	public final java.lang.Long getProgress_Long(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Progress_Long.toString());
	}

	/**
	 * Set value of Progress_Long
	 * @param progress_long
	 */
	public final void setProgress_Long(java.lang.Long progress_long)
	{
		setProgress_Long(getContext(), progress_long);
	}

	/**
	 * Set value of Progress_Long
	 * @param context
	 * @param progress_long
	 */
	public final void setProgress_Long(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long progress_long)
	{
		getMendixObject().setValue(context, MemberNames.Progress_Long.toString(), progress_long);
	}

	/**
	 * @return value of DisplayText
	 */
	public final java.lang.String getDisplayText()
	{
		return getDisplayText(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayText
	 */
	public final java.lang.String getDisplayText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayText.toString());
	}

	/**
	 * Set value of DisplayText
	 * @param displaytext
	 */
	public final void setDisplayText(java.lang.String displaytext)
	{
		setDisplayText(getContext(), displaytext);
	}

	/**
	 * Set value of DisplayText
	 * @param context
	 * @param displaytext
	 */
	public final void setDisplayText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displaytext)
	{
		getMendixObject().setValue(context, MemberNames.DisplayText.toString(), displaytext);
	}

	/**
	 * @return value of Progress_Entity
	 */
	public final progresbar.proxies.Entity getProgress_Entity() throws com.mendix.core.CoreException
	{
		return getProgress_Entity(getContext());
	}

	/**
	 * @param context
	 * @return value of Progress_Entity
	 */
	public final progresbar.proxies.Entity getProgress_Entity(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		progresbar.proxies.Entity result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Progress_Entity.toString());
		if (identifier != null)
			result = progresbar.proxies.Entity.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Progress_Entity
	 * @param progress_entity
	 */
	public final void setProgress_Entity(progresbar.proxies.Entity progress_entity)
	{
		setProgress_Entity(getContext(), progress_entity);
	}

	/**
	 * Set value of Progress_Entity
	 * @param context
	 * @param progress_entity
	 */
	public final void setProgress_Entity(com.mendix.systemwideinterfaces.core.IContext context, progresbar.proxies.Entity progress_entity)
	{
		if (progress_entity == null)
			getMendixObject().setValue(context, MemberNames.Progress_Entity.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Progress_Entity.toString(), progress_entity.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return progressMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final progresbar.proxies.Progress that = (progresbar.proxies.Progress) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ProgresBar.Progress";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
