// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package progresbar.proxies;

public class Progress_Demo
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject progress_DemoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ProgresBar.Progress_Demo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Progress("Progress"),
		BootstrapStyle1("BootstrapStyle1"),
		BootstrapStyle2("BootstrapStyle2"),
		BootstrapStyle3("BootstrapStyle3"),
		BootStrapStyle4("BootStrapStyle4");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Progress_Demo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ProgresBar.Progress_Demo"));
	}

	protected Progress_Demo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject progress_DemoMendixObject)
	{
		if (progress_DemoMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("ProgresBar.Progress_Demo", progress_DemoMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ProgresBar.Progress_Demo");

		this.progress_DemoMendixObject = progress_DemoMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Progress_Demo.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static progresbar.proxies.Progress_Demo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return progresbar.proxies.Progress_Demo.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static progresbar.proxies.Progress_Demo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new progresbar.proxies.Progress_Demo(context, mendixObject);
	}

	public static progresbar.proxies.Progress_Demo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return progresbar.proxies.Progress_Demo.initialize(context, mendixObject);
	}

	public static java.util.List<progresbar.proxies.Progress_Demo> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<progresbar.proxies.Progress_Demo> result = new java.util.ArrayList<progresbar.proxies.Progress_Demo>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//ProgresBar.Progress_Demo" + xpathConstraint))
			result.add(progresbar.proxies.Progress_Demo.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Progress
	 */
	public final java.lang.Integer getProgress()
	{
		return getProgress(getContext());
	}

	/**
	 * @param context
	 * @return value of Progress
	 */
	public final java.lang.Integer getProgress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Progress.toString());
	}

	/**
	 * Set value of Progress
	 * @param progress
	 */
	public final void setProgress(java.lang.Integer progress)
	{
		setProgress(getContext(), progress);
	}

	/**
	 * Set value of Progress
	 * @param context
	 * @param progress
	 */
	public final void setProgress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer progress)
	{
		getMendixObject().setValue(context, MemberNames.Progress.toString(), progress);
	}

	/**
	 * Set value of BootstrapStyle1
	 * @param bootstrapstyle1
	 */
	public final progresbar.proxies.bootstrapStyle getBootstrapStyle1()
	{
		return getBootstrapStyle1(getContext());
	}

	/**
	 * @param context
	 * @return value of BootstrapStyle1
	 */
	public final progresbar.proxies.bootstrapStyle getBootstrapStyle1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.BootstrapStyle1.toString());
		if (obj == null)
			return null;

		return progresbar.proxies.bootstrapStyle.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of BootstrapStyle1
	 * @param bootstrapstyle1
	 */
	public final void setBootstrapStyle1(progresbar.proxies.bootstrapStyle bootstrapstyle1)
	{
		setBootstrapStyle1(getContext(), bootstrapstyle1);
	}

	/**
	 * Set value of BootstrapStyle1
	 * @param context
	 * @param bootstrapstyle1
	 */
	public final void setBootstrapStyle1(com.mendix.systemwideinterfaces.core.IContext context, progresbar.proxies.bootstrapStyle bootstrapstyle1)
	{
		if (bootstrapstyle1 != null)
			getMendixObject().setValue(context, MemberNames.BootstrapStyle1.toString(), bootstrapstyle1.toString());
		else
			getMendixObject().setValue(context, MemberNames.BootstrapStyle1.toString(), null);
	}

	/**
	 * Set value of BootstrapStyle2
	 * @param bootstrapstyle2
	 */
	public final progresbar.proxies.bootstrapStyle getBootstrapStyle2()
	{
		return getBootstrapStyle2(getContext());
	}

	/**
	 * @param context
	 * @return value of BootstrapStyle2
	 */
	public final progresbar.proxies.bootstrapStyle getBootstrapStyle2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.BootstrapStyle2.toString());
		if (obj == null)
			return null;

		return progresbar.proxies.bootstrapStyle.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of BootstrapStyle2
	 * @param bootstrapstyle2
	 */
	public final void setBootstrapStyle2(progresbar.proxies.bootstrapStyle bootstrapstyle2)
	{
		setBootstrapStyle2(getContext(), bootstrapstyle2);
	}

	/**
	 * Set value of BootstrapStyle2
	 * @param context
	 * @param bootstrapstyle2
	 */
	public final void setBootstrapStyle2(com.mendix.systemwideinterfaces.core.IContext context, progresbar.proxies.bootstrapStyle bootstrapstyle2)
	{
		if (bootstrapstyle2 != null)
			getMendixObject().setValue(context, MemberNames.BootstrapStyle2.toString(), bootstrapstyle2.toString());
		else
			getMendixObject().setValue(context, MemberNames.BootstrapStyle2.toString(), null);
	}

	/**
	 * Set value of BootstrapStyle3
	 * @param bootstrapstyle3
	 */
	public final progresbar.proxies.bootstrapStyle getBootstrapStyle3()
	{
		return getBootstrapStyle3(getContext());
	}

	/**
	 * @param context
	 * @return value of BootstrapStyle3
	 */
	public final progresbar.proxies.bootstrapStyle getBootstrapStyle3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.BootstrapStyle3.toString());
		if (obj == null)
			return null;

		return progresbar.proxies.bootstrapStyle.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of BootstrapStyle3
	 * @param bootstrapstyle3
	 */
	public final void setBootstrapStyle3(progresbar.proxies.bootstrapStyle bootstrapstyle3)
	{
		setBootstrapStyle3(getContext(), bootstrapstyle3);
	}

	/**
	 * Set value of BootstrapStyle3
	 * @param context
	 * @param bootstrapstyle3
	 */
	public final void setBootstrapStyle3(com.mendix.systemwideinterfaces.core.IContext context, progresbar.proxies.bootstrapStyle bootstrapstyle3)
	{
		if (bootstrapstyle3 != null)
			getMendixObject().setValue(context, MemberNames.BootstrapStyle3.toString(), bootstrapstyle3.toString());
		else
			getMendixObject().setValue(context, MemberNames.BootstrapStyle3.toString(), null);
	}

	/**
	 * Set value of BootStrapStyle4
	 * @param bootstrapstyle4
	 */
	public final progresbar.proxies.bootstrapStyle getBootStrapStyle4()
	{
		return getBootStrapStyle4(getContext());
	}

	/**
	 * @param context
	 * @return value of BootStrapStyle4
	 */
	public final progresbar.proxies.bootstrapStyle getBootStrapStyle4(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.BootStrapStyle4.toString());
		if (obj == null)
			return null;

		return progresbar.proxies.bootstrapStyle.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of BootStrapStyle4
	 * @param bootstrapstyle4
	 */
	public final void setBootStrapStyle4(progresbar.proxies.bootstrapStyle bootstrapstyle4)
	{
		setBootStrapStyle4(getContext(), bootstrapstyle4);
	}

	/**
	 * Set value of BootStrapStyle4
	 * @param context
	 * @param bootstrapstyle4
	 */
	public final void setBootStrapStyle4(com.mendix.systemwideinterfaces.core.IContext context, progresbar.proxies.bootstrapStyle bootstrapstyle4)
	{
		if (bootstrapstyle4 != null)
			getMendixObject().setValue(context, MemberNames.BootStrapStyle4.toString(), bootstrapstyle4.toString());
		else
			getMendixObject().setValue(context, MemberNames.BootStrapStyle4.toString(), null);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return progress_DemoMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final progresbar.proxies.Progress_Demo that = (progresbar.proxies.Progress_Demo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ProgresBar.Progress_Demo";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
