// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
/**
 * @returns {Promise.<void>}
 */
export async function clearCachedSessionData(): Promise<void> {
    // BEGIN USER CODE
    await mx.session.clearCachedSessionData();
    // END USER CODE
}
