// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
/**
 * @returns {Promise.<void>}
 */
export async function ClearCachedSessionData(): Promise<void> {
    // BEGIN USER CODE
    if (mx.session && mx.session.clearCachedSessionData === undefined) {
        return Promise.reject(
            new Error("JS action 'Clear cached session data' is not supported prior to Mendix client v9.14")
        );
    }

    await mx.session.clearCachedSessionData();
    // END USER CODE
}
