// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package appcloudservices.actions;

import java.util.ArrayList;
import java.util.List;
import org.apache.commons.lang.RandomStringUtils;
import org.apache.commons.lang.math.RandomUtils;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Generate a valid strong random password for Mendix user
 */
public class GenerateRandomPassword extends CustomJavaAction<java.lang.String>
{
	private java.lang.Long length;

	public GenerateRandomPassword(IContext context, java.lang.Long length)
	{
		super(context);
		this.length = length;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String _pw_charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
				+ "abcdefghijklmnopqrstuvwxyz"
				+ "!@#$%^&*()+-_[]{}=,./\\|~`'\":;<>?" + "1234567890";
		
		if (length < 5)
			throw new IllegalArgumentException(
					"Password length should at least be 4");

		StringBuilder sb = new StringBuilder();
		for (int i = 0; i < length - 4; i++)
			sb.append(_pw_charset.charAt(RandomUtils.nextInt(_pw_charset
					.length())));

		// make sure it is strong
		sb.append(RandomStringUtils.random(1, "ABCDEFGHIJKLMNOPQRSTUVWXYZ"));
		sb.append(RandomStringUtils.random(1, "abcdefghijklmnopqrstuvwxyz"));
		sb.append(RandomStringUtils.random(1,
				"!@#$%^&*()+-_[]{}=,./\\|~`'\":;<>?"));
		sb.append(RandomStringUtils.random(1, "1234567890"));

		// do shuffle
		List<String> base = new ArrayList<String>();
		StringBuilder result = new StringBuilder();

		for (char c : sb.toString().toCharArray())
			base.add(String.valueOf(c));

		while (base.size() > 0)
			result.append(base.remove(RandomUtils.nextInt(base.size())));

		return result.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GenerateRandomPassword";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
