// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import ReactNative from "react-native";

/**
 * @param {string} title - This field is required.
 * @param {string} message
 * @returns {boolean}
 */
function ShowMessage(title?: string, message?: string): Promise<boolean> {
    // BEGIN USER CODE

    if (!title) {
        throw new TypeError("Input parameter 'Title' is required");
    }

    if (navigator && navigator.product === "ReactNative") {
        const Alert: typeof ReactNative.Alert = require("react-native").Alert;

        return new Promise(resolve => {
            Alert.alert(title, message, [{ text: "OK", onPress: () => resolve(true) }]);
        });
    }

    if (window && window.alert) {
        window.alert(`${title}\n\n${message || ""}`);
        return Promise.resolve(true);
    }

    return Promise.resolve(false);

    // END USER CODE
}
