// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import ReactNative from "react-native";

/**
 * @param {string} title - This field is required.
 * @param {string} message
 * @param {string} cancelText - Set to empty to use default text 'Cancel'.
 * @param {string} okText - Set to empty to use default text 'OK'.
 * @returns {boolean}
 */
function ShowConfirmation(title?: string, message?: string, cancelText?: string, okText?: string): Promise<boolean> {
    // BEGIN USER CODE

    if (!title) {
        throw new TypeError("Input parameter 'Title' is required");
    }

    cancelText = cancelText || "Cancel";
    okText = okText || "OK";

    if (navigator && navigator.product === "ReactNative") {
        const Alert: typeof ReactNative.Alert = require("react-native").Alert;

        return new Promise(resolve => {
            Alert.alert(title, message, [
                { text: cancelText, onPress: () => resolve(false), style: "cancel" },
                { text: okText, onPress: () => resolve(true) }
            ]);
        });
    }

    if (window && window.confirm) {
        const result = window.confirm(`${title}\n\n${message || ""}`);
        return Promise.resolve(result);
    }

    return Promise.resolve(false);

    // END USER CODE
}
