// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

import ReactNative from "react-native";

/**
 * @param {string} title - This field is required.
 * @param {string} message
 * @returns {string}
 */
function ShowMessage(title?: string, message?: string): Promise<void> {
    // BEGIN USER CODE
    // Documentation https://facebook.github.io/react-native/docs/alert

    const Alert: typeof ReactNative.Alert = require("react-native").Alert;

    if (!title) {
        throw new TypeError("Input parameter 'Title' is required");
    }

    return new Promise(resolve => {
        Alert.alert(title, message, [{ text: "OK", onPress: () => resolve() }]);
    });

    // END USER CODE
}
