// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

/**
 * @returns {boolean}
 */
function RequestLocationPermission(): boolean {
    // BEGIN USER CODE

    if (navigator && navigator.geolocation) {
        if (navigator.geolocation.requestAuthorization) {
            navigator.geolocation.requestAuthorization();
        }
        return true;
    }

    return false;

    // END USER CODE
}
