// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} sampleparameter - Parameter description documentation.
 * @returns {Promise.<boolean>}
 */
export async function Sample_Action(sampleparameter) {
    // BEGIN USER CODE
    throw new Error("JavaScript action was not implemented");
    // END USER CODE
}
