"use strict";
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.
/**
 * @param {string} searchQuery
 * @returns {boolean}
 */
// eslint-disable-next-line no-unused-vars,@typescript-eslint/no-unused-vars
function SearchContacts(searchQuery) {
    // BEGIN USER CODE
    // Documentation: https://github.com/apache/cordova-plugin-contacts
    return new Promise((resolve, reject) => {
        if (!navigator.contacts) {
            return reject(
                new Error("SearchContacts action requires cordova-plugin-contacts to be installed in the app")
            );
        }
        const searchedFields = [
            "displayName",
            "nickname",
            "name",
            "name.givenName",
            "name.middleName",
            "name.familyName",
            "emails",
            "phoneNumbers"
        ];
        navigator.contacts.find(
            searchedFields,
            contacts => {
                Promise.all(contacts.map(contact => createMxObject(contact)))
                    .then(objects => resolve(objects))
                    .catch(error => reject(error));
            },
            error => reject(errorMessage(error)),
            { filter: searchQuery, desiredFields: searchedFields }
        );
    });
    function createMxObject(contact) {
        return new Promise((resolve, reject) => {
            mx.data.create({
                entity: "HybridMobileActions.Contact",
                callback: mxObject => {
                    const name = contact.displayName || contact.nickname || (contact.name && contact.name.formatted);
                    if (name) {
                        mxObject.set("DisplayName", name);
                    }
                    if (contact.name && contact.name.givenName) {
                        mxObject.set("FirstName", contact.name.givenName);
                    }
                    if (contact.name && contact.name.middleName) {
                        mxObject.set("MiddleName", contact.name.middleName);
                    }
                    if (contact.name && contact.name.familyName) {
                        mxObject.set("LastName", contact.name.familyName);
                    }
                    const email = contact.emails && contact.emails[0].value;
                    if (email) {
                        mxObject.set("Email", email);
                    }
                    const phoneNumber = contact.phoneNumbers && contact.phoneNumbers[0].value;
                    if (phoneNumber) {
                        mxObject.set("PhoneNumber", phoneNumber);
                    }
                    resolve(mxObject);
                },
                error: () => reject(new Error("Could not create 'HybridMobileActions.Contact' object"))
            });
        });
    }
    function errorMessage(error) {
        switch (error.code) {
            case 0 /* UNKNOWN_ERROR */:
                return "Found an unknown error while handling the request.";
            case 1 /* INVALID_ARGUMENT_ERROR */:
                return "Invalid argument found.";
            case 2 /* TIMEOUT_ERROR */:
                return "Operation timed out.";
            case 3 /* PENDING_OPERATION_ERROR */:
                return "Pending operation error.";
            case 4 /* IO_ERROR */:
                return "IO error encountered.";
            case 5 /* NOT_SUPPORTED_ERROR */:
                return "Operation not supported.";
            case 6 /* OPERATION_CANCELLED_ERROR */:
                return "Operation cancelled.";
            case 20 /* PERMISSION_DENIED_ERROR */:
                return "Permission denied.";
        }
        return "Error code undefined";
    }
    // END USER CODE
}
