"use strict";
// <reference path="../types/cordova-clipboard.d.ts" />
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.
/**
 * @param {string} content - This field is required.
 * @returns {boolean}
 */
// eslint-disable-next-line no-unused-vars,@typescript-eslint/no-unused-vars
function SetClipboardContent(content) {
    // BEGIN USER CODE
    // Documentation https://www.npmjs.com/package/cordova-clipboard
    // Requires cordova-clipboard plugin
    if (!cordova.plugins || !cordova.plugins.clipboard) {
        throw new Error("SetClipboardContent action requires cordova-clipboard plugin to be installed in the app");
    }
    if (!content) {
        throw new Error("Input parameter 'Content' is required");
    }
    cordova.plugins.clipboard.copy(content);
    return true;
    // END USER CODE
}
