// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mendixsso.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mendixsso.implementation.oidp.IdentityProviderMetaDataCache;
import mendixsso.proxies.constants.Constants;

public class GetTokenEndpointURI extends CustomJavaAction<java.lang.String>
{
	public GetTokenEndpointURI(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        try {
            return IdentityProviderMetaDataCache.getInstance().getIdentityProviderMetaData().getProviderMetadata().getTokenEndpointURI().toString();
        } catch (Exception e) {
            Core.getLogger(Constants.getLogNode()).error("Something went wrong while retrieving the token endpoint URI from cache", e);
            return null;
        }
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTokenEndpointURI";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
