name: "Start the runtime"
description: "Start the runtime in preparation of the native e2e tests"
inputs:
  mda-file:
    description: "Path to the deployment package"
    required: true
  mendix-version:
    description: "Mendix version to use for the runtime"
    required: true
runs:
  using: composite
  steps:
    - name: "Setup Python"
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: "Install Python dependencies"
      run: pip install pyaml httplib2
      shell: bash
    - name: "Setup Java 11"
      id: setup-java
      uses: actions/setup-java@16cca5479d7c6b6843f6a6515640ba33c6501543 #3.4.0
      with:
        distribution: "temurin"
        java-version: "11"
    - name: "Extract deployment package"
      run: |
        mkdir project
        unzip -qq ${{ inputs.mda-file }} -d project
        cp .github/configs/m2ee-native.yml project/m2ee-native.yml
        sed -i -- 's=$ROOT_PATH=${{ github.workspace }}=g' project/m2ee-native.yml
        sed -i -- 's=$JAVA_HOME=${{ steps.setup-java.outputs.path }}=g' project/m2ee-native.yml
      shell: bash
    - name: "Setup m2ee"
      run: |
        mkdir -p var/log var/opt/m2ee var/run bin tmp
        git clone https://github.com/KevinVlaanderen/m2ee-tools.git tmp/m2ee
        mv tmp/m2ee/src/* var/opt/m2ee
        chmod a=rwx var/log/ var/run/
        echo "#!/bin/bash -x" > bin/m2ee
        echo "python3 var/opt/m2ee/m2ee.py \$@" >>bin/m2ee
        chmod +x bin/m2ee
      shell: bash
    - name: "Setup mxruntime"
      run: |
        mkdir -p ${{ github.workspace }}/project/runtimes ${{ github.workspace }}/project/data/model-upload ${{ github.workspace }}/project/data/database ${{ github.workspace }}/project/data/files ${{ github.workspace }}/project/data/tmp
        wget -q https://cdn.mendix.com/runtime/mendix-${{ inputs.mendix-version }}.tar.gz -O tmp/runtime.tar.gz
        tar xfz tmp/runtime.tar.gz --directory ${{ github.workspace }}/project/runtimes
        rm tmp/runtime.tar.gz
      shell: bash
    - name: "Start mxruntime"
      run: bin/m2ee -c ${{ github.workspace }}/project/m2ee-native.yml --verbose --yolo start
      shell: bash
