name: Publish widget data
on:
  push:
    branches:
      - master
    paths:
      - packages/pluggableWidgets/**/package.json
      - packages/customWidgets/**/package.json
      - packages/pluggableWidgets/**/src/*.xml
      - packages/customWidgets/**/src/*.xml
      - scripts/data/**/*
jobs:
  publish-data:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking-out code"
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
        with:
          submodules: false
      - name: "Defining node version"
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2
        with:
          node-version-file: '.nvmrc'
      - name: "Defining cache"
        uses: c-hive/gha-npm-cache@2de807f96074eec2c36c2d321c20724cd04112dd # v1.1.0
      - name: "Installing dependencies"
        run: npm install
      - name: "Collecting widgets overview data"
        run: npm run update:widgets-overview
      - name: "Creating pull request"
        id: cpr
        uses: peter-evans/create-pull-request@dcd5fd746d53dd8de555c0f10bca6c35628be47a # v3
        with:
          token: ${{ secrets.GH_PAT }}
          branch: build/update-widgets-data
          delete-branch: true
          commit-message: 'chore: update widgets data file'
          title: 'chore: Update widgets data file'
          draft: false
          add-paths: 'data/widgets.json'
      - name: "Enabling auto merge"
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@d2ede5636b3febc92809259995e643565e675aab # v1
        with:
          token: ${{ secrets.GH_PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase
